### ISSUE TITLE
New Column By Example Intermittent Errors: Code Generation Sometimes Fails

### ISSUE THREAD

**Issue by MrDamienJones** [microsoft/vscode-data-wrangler#100]
## Environment data

-   VS Code version: 1.84.0
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.18.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1003070148
-   Python Extension version (available under the Extensions sidebar): v2023.20.0
-   OS (Windows | Mac | Linux distro) and version: WSL2 - Windows_NT x64 10.0.19045
-   Pandas version: 2.0.3
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used: virtualenv

From VCode:

Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

## Expected behaviour

Using New Column By Example, every time Flash Fill is able to populate column using target columns selected.

## Actual behaviour

Code generation fails when pattern is submitted.  This is not consistent and restarts, reloads etc seem to have no effect.

This behaviour can be seen at https://youtu.be/XAIvUW5c9ww?si=c8f3vo-VGsJtDi90&t=1347

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Select New Column By Example
2. Select target columns
3. Enter pattern into new column cell.

## Logs

None supplied

**Comment by pwang347** [comment]
Hi @MrDamienJones, thanks for reporting this issue!

If possible, could you please share the dataset (or a sample one) and the example input that you expected to work but didn't? From what I can see, the scenario you demo'd in the video should work, but if not then it could be a bug with the detection AI and we'll try to fix it.

**Comment by MrDamienJones** [comment]
Hi @pwang347,

Happy to help!  The data is from https://sale-harriers.niftyentries.com/Results/Sale-Sizzler-1-2023 - there's a download button below the **Club** filter which downloads the CSV.

My target columns were **Gender** and **Category**.  My expected output was typing **Male Under 20** to populate the new column with concatenated values for all runners.  I recorded a GIF at https://amazonwebshark.com/new-stars-of-data-retrospective/#:~:text=This%20GIF%20from%20the%20demo%20shows%20how%20the%20Gender%20Category%20column%20is%20created%3A showing what I expected to happen.

Separately, love the Wrangler :) Nice work!

**Comment by pwang347** [comment]
@MrDamienJones Thanks a lot for sharing, and I appreciate the kind feedback!

I do have a hunch for what's happening here, and I suspect that it's a 5s timeout mechanism kicking in (we generally don't expect the detection to run that long, so pre-emptively short-circuit it). Based on the recording you have it seems like it's taking about 5s before erroring out.

You mentioned that this behaviour isn't exactly consistent - when it is working does it also take a few seconds or is it fast?

**Comment by MrDamienJones** [comment]
Hi,

The GIF I linked to is in real-time.  From experience, failures of the kind shown in the demo are very rare (which is why I kept in in the demo to begin with!) and not something I can force to happen.  I would say I get a 95% success rate, and in these cases it's more or less instant.

**Comment by pwang347** [comment]
> Hi,
> 
> The GIF I linked to is in real-time. From experience, failures of the kind shown in the demo are very rare (which is why I kept in in the demo to begin with!) and not something I can force to happen. I would say I get a 95% success rate, and in these cases it's more or less instant.

Got it. Thanks for the extra details, will investigate and see what I can find!

**Comment by kycutler** [comment]
Hi @MrDamienJones, this issue should now be fixed in the latest pre-release version of Data Wrangler. Please give it a try and feel free to re-open this issue if it persists.

Thanks for trying Data Wrangler!
