### ISSUE TITLE
Just pass df instead of df.copy() to clean_data?

### ISSUE THREAD

**Issue by cdeil** [microsoft/vscode-data-wrangler#106]
Currently you're exporting this code to clean a DataFrame:
```
import pandas as pd

def clean_data(df):
    # Drop column: 'Survived'
    df = df.drop(columns=['Survived'])
    return df

# Loaded variable 'df' from URI: /Users/cdeil/.vscode/extensions/ms-toolsai.datawrangler-0.20.0/walkthrough.csv
df = pd.read_csv(r'/Users/cdeil/.vscode/extensions/ms-toolsai.datawrangler-0.20.0/walkthrough.csv', engine='pyarrow')

df_clean = clean_data(df.copy())
df_clean.head()
```

I think you can simply pass in `df` instead of `df.copy()` into `clean_data`?

Do you still have cases where you need the explicit and in most transforms unnecessary copy ?

**Comment by pwang347** [comment]
Hi @cdeil! Thanks for opening this issue.

It is true that the built-in operations we support generally do not mutate the variables in-place. However, we allow users to author custom code and for this scenario we would like to ensure that the original variable is unchanged. So for now this behaviour is as-designed as we believe the perf implications to not be severe when included in this case.

Please feel free to re-open the issue if you disagree. Thanks!

**Comment by cdeil** [comment]
The defensive copy is mostly historic and now the recommended modern way is to use copy-on-write: https://youtu.be/z47QwqDUKTo?si=KWxAajVpKTkG2kp5

So especially with something like data wrangler where you have new users if you don't copy you might prevent them from shooting themselves in the foot, but also you are propagating and teaching the no longer recommended way to use pandas (or other dataframe libs, polars, spark, ....).

Personally with a new tool like data wrangler I would have directly gone with the modern performant approach and only mention that sometimes in old pandas you might want to make a copy (just link to one of the many existing resources on that). But choosing the safe defensive copy for now is also a reasonable choice of course. I'll just delete it every time I use data wrangler and remember to get the cleaner and more performant code.
