### ISSUE TITLE
Feature request: Support opening on `display()` command

### ISSUE THREAD

**Issue by celynw** [microsoft/vscode-data-wrangler#107]
I got into the habit of using the `display()` function. It does the same thing as when you put a variable name at the bottom of a cell, except it can be used at any point in the cell, and it may be used multiple times per cell. (I believe [this is the documentation](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#module-IPython.display))

It seems that Data Wrangler doesn't offer to open in these cases, although the output is (seemingly) identical.

Is this a possibility?

![image](https://github.com/microsoft/vscode-data-wrangler/assets/3299161/c9afaa12-35c7-4ed3-adbe-2693726c6f25)

**Comment by pwang347** [comment]
Hi @celynw, thanks for opening this issue!

Would it be sufficient for your use case if we supported `display(df)` only when it appears at the end of the cell?
With the current APIs available, there would be some limitations with how we can make sure it isn't confusing when `display` is called in a function (which means no variable attached), when `display` is called and then the variable is modified, etc.

**Comment by celynw** [comment]
Ah I see. I didn't know anything about how the implementation would work. Having this functionality at the end of the cell would certainly be useful! This is how I most commonly use it.

Since nobody raised this issue before, I hope this request doesn't sound too much of a niche and personal use-case. Happy for others to weigh in

**Comment by pwang347** [comment]
Hi @celynw, just letting you know that a change for this was merged and you can expect to see this functionality in the newest pre-release. Cheers!
