### ISSUE TITLE
Failed to launch kernel

### ISSUE THREAD

**Issue by Georgewxm** [microsoft/vscode-data-wrangler#108]
Type: <b>Bug</b>

-> Right click any csv file in Windows file explorer
-> Open in VS Code Insiders
-> Right click on Data Wrangler logo on top right corner
-> Connect to runtime
-> Click local Python Interpreter (the one I always used)
-> Get error: Failed to launch kernel.
Error: Unable to start Kernel 'Python 3.9.13' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
Error: Unable to start Kernel 'Python 3.9.13' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    at c:\Users\27151\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.10.1100000000-win32-x64\out\extension.node.js:24:87501
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Lv.launch (c:\Users\27151\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.10.1100000000-win32-x64\out\extension.node.js:24:87543)

Extension version: 0.21.2
VS Code version: Code - Insiders 1.85.0-insider (b3b84b5239037a2f0ef8499306df9a3bacda4105, 2023-11-28T12:02:59.475Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (18.51GB free)|
|Process Argv|--crash-reporter-id 5846b696-4e62-4d0b-bea7-a576080e9ff6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by pwang347** [comment]
Hi @Georgewxm! Thanks for opening this issue.

Seems like you are running into an issue with the Jupyter extensions' kernel launch, so you should be able to open an issue [there](https://github.com/microsoft/vscode-jupyter/issues/new/choose). I would also highly recommend adding the logs from `Jupyter` in the `Outputs` panel if available.

Closing for now, but feel free to let me know if you need any more info. Thanks!
