### ISSUE TITLE
No way to pick a different runtime

### ISSUE THREAD

**Issue by jerrylin96** [microsoft/vscode-data-wrangler#111]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2023.10.1100000000
-   Python extension version: 2023.20.0
-   .NET Install Tool for Extension Authors extension version: 2.0.0
-   Python package dependencies:

```json
{
  "satisfied": {
    "pandas": {
      "installedVersion": "1.4.3",
      "requiredVersion": "0.25.2"
    }
  },
  "unsatisfied": {}
}
```

I'm not able to choose a different runtime. Also, it's unclear when I'm running exceeding available RAM.

Extension version: 0.22.0
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:
Remote OS version: Linux x64 4.18.0-193.28.1.el8_2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id e2493ef2-63f6-4853-8d76-bd91aaff010d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bridges2.psc.edu|
|OS|Linux x64 4.18.0-193.28.1.el8_2.x86_64|
|CPUs|AMD EPYC 7742 64-Core Processor (256 x 3291)|
|Memory (System)|251.09GB (105.79GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by pwang347** [comment]
Hi @jerrylin96! You can change the runtime from the bottom right corner here:
<img width="244" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/8560030/0ee29ba6-e093-41ad-af95-e3b0d8ab4061">

Regarding RAM, I would recommend taking a look at the VS Code marketplace to see if there are any good system monitor extensions given that everything is currently running locally. You might be able to get better visualizations/breakdowns there.

Thanks for trying Data Wrangler!
