### ISSUE TITLE
Opening an Excel file of multiple sheets directly through Data Wrangler

### ISSUE THREAD

**Issue by rbasa349** [microsoft/vscode-data-wrangler#117]
## Environment data

-   VS Code version: 1.85.0
-   Data Wrangler Extension version (available under the Extensions sidebar): v0.22.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1003402403
-   Python Extension version (available under the Extensions sidebar): v2023.22.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11/macOS 14
-   Pandas version: 2.1.4
-   Python and/or Anaconda version: 3.11/-
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

When opening an Excel file directly through Data Wrangler, it opens an Excel file consisting of several sheets and allows you to switch between them (similar to Excel)
or
When opening an Excel file directly through Data Wrangler, it opens an Excel file with multiple sheets and allows you to choose which sheet to open.

## Actual behaviour

Data Wrangler always opens only the first Excel sheet

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open Excel file directly through Data Wrangler

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Not needed
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @rbasa349, thanks for creating this feature request!

This item is currently in our backlog and is part of an effort to support greater customization of the import options. We will follow up on this thread as we make progress.

Thank you for trying Data Wrangler!

**Comment by kycutler** [comment]
Hi @rbasa349, good news! This is now possible in the latest pre-release version of Data Wrangler.

To load a sheet other than the first, after opening the Excel file (and before applying any operations), select the first cleaning step to edit it, and then adjust the "Page number" parameter within the operations panel (you can also use the up/down arrow keys to quickly change the value). You should see the grid update to reflect the contents on that page. Then just click "Update" to save when ready.

Closing this issue as it should now be resolved, but please let us know if you have any issues or additional feedback!
