### ISSUE TITLE
feature request: merge/join tables

### ISSUE THREAD

**Issue by julen3** [microsoft/vscode-data-wrangler#120]
It would be really nice if there was an operation to join the table I'm working with with another one. Ideally, when selecting this operation, a window would open up asking me for the source of the other table that I want to join, as well as the columns that the join operation is going to be based on and the type of join that I want to do (left outer, left inner, etc.) It would also display the number of matching rows.

Esentially, it would use the pandas **merge** function, used to combine two DataFrames based on one or more common columns, and the window that pops up would look similar to the one from Power Query when selecting this kind of operation: https://learn.microsoft.com/en-us/power-query/merge-queries-overview

**Comment by pwang347** [comment]
Thanks for opening this request @julen3, and hope you're having a great new year!

I've added your notes to the following issue and we can continue the discussion there: https://github.com/microsoft/vscode-data-wrangler/issues/24
