### ISSUE TITLE
Do not open automatically in source control panel

### ISSUE THREAD

**Issue by psychelzh** [microsoft/vscode-data-wrangler#123]
When visualizing the differences between commits in source control panel, data wrangler is very annoying because it did not show the differences.

**Comment by pwang347** [comment]
Hi @psychelzh, thanks for opening this issue!

Could you clarify a bit more what you mean by opening in source control panel? Do you mean that you had the source control panel open, but Data Wrangler stole visibility from it when the Data Wrangler panels are shown?

**Comment by psychelzh** [comment]
For example, if I have tracked one `.tsv` file in git, and I am checking the differences of my working copy by click the file in the source control panel, then the Data Wrangler will open that file without showing the differences.

**Comment by kycutler** [comment]
Hi @psychelzh, thank you for reporting this issue! We have implemented a fix to prevent Data Wrangler from being used to open diffs from source control. This is available now in the latest pre-release version of Data Wrangler and will be available in the next stable release as well. Please give it a try, and feel free to re-open this issue if you still see problems!
