### ISSUE TITLE
Failed to update data frame: module 'pandas.io.json' has no attribute 'dumps'

### ISSUE THREAD

**Issue by LisaHoek** [microsoft/vscode-data-wrangler#125]
Hi, datawrangler worked on my old laptop, but now I installed it on my new laptop and I get the following error when opening on a df:

_Failed to update data frame: module 'pandas.io.json' has no attribute 'dumps'_

What can I do to resolve this?

Thanks in advance!

**Comment by sfeuerwerker** [comment]
second the above issue, except on the same computer and environment where it has previously worked

**Comment by kycutler** [comment]
Thank you for raising the issue! It looks like Pandas 2.2.0 includes a change that broke us. We have a fix and are working on publishing it to both stable and pre-release channels. That should be done in the next few hours -- I'll reply here when the fix is available.

**Comment by kycutler** [comment]
The fix has been deployed. Please update to the latest version of the Data Wrangler extension (`0.22.3` stable, or `0.23.5` pre-release) and reload VS Code to resolve the issue.

**Comment by JohannesStueber** [comment]
Can confirm it's resolved. Thank you for the fast fix 👍

**Comment by LisaHoek** [comment]
Yes, it works, thank you for the quick action!
