### ISSUE TITLE
Data Wrangler attempts to reinstall python and Jupyter ext when I already have them

### ISSUE THREAD

**Issue by BBoggia** [microsoft/vscode-data-wrangler#129]
## Environment data

-   VS Code version: 1.85.2
-   Data Wrangler Extension version (available under the Extensions sidebar): v0.25.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1100101639
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: macOS Sonoma 14.1.1
-   Pandas version: 2.1.4
-   Python and/or Anaconda version: Python 3.10.10 & conda 23.10.0 (miniforge)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

After selecting 'Connect to runtime' and 'Connect using local Python interpreter', it should allow me to select one of my local runtimes

## Actual behaviour

After selecting 'Connect to runtime' and 'Connect using local Python interpreter', it states that I need the Jupyter and Python extensions and asks if I want to install them. After selecting yes, it hangs for a while saying 'Installing Python extension (includes Jupyter extension)' before eventually failing with the error 'Failed to launch kernel. Error: undefined'.

## Steps to reproduce:

1. N/A

## Logs
<img width="462" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/18659543/c9d4b72c-e992-479d-8b73-8664d178da33">

<img width="474" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/18659543/d20a867f-415c-4e24-a119-241d650db64d">

**Comment by pwang347** [comment]
Hi @BBoggia, thanks for reporting this issue! Just wanted to check a few things:
1. Are you still running into the same issue even after reloading VS Code (and Data Wrangler)?
2. Does the kernel selector work in a Jupyter notebook?

Thanks!

**Comment by BBoggia** [comment]
No problem @pwang347. Yeah, I just tried it again after fully shutting down VS Code and the issue is still happening. Jupyter notebook is also working fine and the kernel selector works without issue.

The codes irrelevant but you can see my Jupyter is running fine in the image below. Also in the bottom left is what happens when I go to the other data wrangler page and try to use 'Connect using local Python interpreter' except now it's giving me a new Jupyter extension error that wasn't there before.

<img width="1313" alt="Screenshot 2024-01-26 at 2 12 41 PM" src="https://github.com/microsoft/vscode-data-wrangler/assets/18659543/f258ced7-75fc-4f53-8f1f-86872157e9b7">

**Comment by pwang347** [comment]
@BBoggia thanks for the response! Are you by any chance using a dev container or perhaps something like WSL?
I am currently suspecting that the issue might be related to https://github.com/microsoft/vscode-remote-release/issues/8074

Note that we're figuring out whether or not the extensions are installed using the built-in VS Code command `vscode.extensions.getExtension(<extension ID>)`, so if something isn't working there it's likely to be an upstream VS Code issue.

**Comment by BBoggia** [comment]
@pwang347 I'm on Mac so not WSL but I am running conda. From what the bug report you linked says I'm guessing thats probably the issue though.

**Comment by pwang347** [comment]
@BBoggia Just an update, I had a chat with @joyceerhl and it seems like this issue primarily occurs when extensions are running on different [extension hosts](https://code.visualstudio.com/api/advanced-topics/extension-host). Could you check if you have this block in your settings.json file (and if so, try removing it?)

```
"extensions.experimental.affinity": {
        "ms-toolsai.jupyter": 1,
        ...
}
```

This setting can be added if you ran the command `Jupyter: Run in Dedicated Extension Host`. I just verified that I can repro the issue if I run this command. Thanks!

**Comment by pwang347** [comment]
If you want to keep your setting, another option is to add this to the map as well:
`"ms-toolsai.datawrangler": 1`

**Comment by BBoggia** [comment]
@pwang347 It looks like adding `"ms-toolsai.datawrangler": 1` seems to have fixed it. I also noticed there was an update that had me reload the extension so I'm not sure which one it was but it's working now. Thanks for your help!

Also I did have those lines in my settings. Would it be better to remove them or leave them with the added DataWrangler setting?

**Comment by pwang347** [comment]
@BBoggia Thanks for confirming! I believe the setting is meant to help improve the performance of the Jupyter extension by making it run in a different context (in the process making it hidden from Data Wrangler). So feel free to just add the Data Wrangler setting if that's something you'd like to keep.

Will close the issue now, but let me know if there's anything else I can help with!
