### ISSUE TITLE
Unable to change the sep while loading the csv file, the default is the ':', but my csv is ',' separated.

### ISSUE THREAD

**Issue by iqbalfarz** [microsoft/vscode-data-wrangler#130]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2023.11.1100101639
-   Python extension version: 2023.22.1
-   .NET Install Tool for Extension Authors extension version: 2.0.1
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.1.4"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

Extension version: 0.24.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.5.0-14-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 1854)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|15.30GB (3.92GB free)|
|Process Argv|--unity-launch --crash-reporter-id d31e5bab-5e15-4244-8f2c-eeb781f7a5d4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30951918
3ef8e399:30949928

```

</details>

**Comment by kycutler** [comment]
Hi @iqbalfarz! The latest version of Data Wrangler attempts to automatically detect the CSV separator, but sometimes it may be incorrect.

By chance would you be able to share the original CSV file (or the top few rows from it)? That would help us improve the detection.

There are two ways you can resolve the issue:
1. In the Data Wrangler extension settings you can uncheck "Auto Detect Csv Delimiter" to disable the automatic detection. All CSV files will then use the `,` separator.
  ![image](https://github.com/microsoft/vscode-data-wrangler/assets/67761731/4b731997-79d0-43a9-83b9-57f281c45bed)

2. In the pre-release version of Data Wrangler, it is possible to change the separator after loading. You can install the pre-release version by viewing the Data Wrangler extension from the Extensions panel in VS Code and selecting "Switch to Pre-Release Version":
  ![image](https://github.com/microsoft/vscode-data-wrangler/assets/67761731/bc115817-d104-4201-9a59-6c6e23190726)
  In this version, after the data loads you can edit the loading step by selecting it in the cleaning steps panel or using the shortcut "Edit" button in the message that appears over the grid after loading:
  ![image](https://github.com/microsoft/vscode-data-wrangler/assets/67761731/ebe91add-05f6-49b2-9518-7d7f2e7efc92)

Hope this helps!

**Comment by kycutler** [comment]
Closing the issue as it should be resolved. But feel free to reopen.
