### ISSUE TITLE
Does not auto-identify Python runtime for project, nor can select a runtime via connect using local Python Interpreter

### ISSUE THREAD

**Issue by epicwhale** [microsoft/vscode-data-wrangler#132]
Type: <b>Bug</b>

# Behaviour
My CSV files are associated to default open with Data Wrangler. It was working fine a few weeks ago. Recently when I open a CSV file in the same project (which has a conda python environment associated for the rest of the project), I am now getting the "Welcome to Data Wrangler" screen with the - "Select a runtime" option

When I tap the "Select a runtime" --> "Connect using local Python interpreter" it shows a box with the "Select Kernel for 'Users/.........' but that box does not autocomplete or suggest any pytho environment for me to pick... How do I set up the python runtime for this CSV file inside my VS code project?

## Expected vs. Actual

Expect it to use (or suggest) one of the python runtimes being used elsewhere in the project either by jupyter or .py files -as the interpreter.

## Steps to reproduce:

1. Open a CSV file with Data Wrangler (as default)

# Diagnostic data

-   Jupyter extension version: 2024.2.2024020801
-   Python extension version: 2024.0.1
-   .NET Install Tool for Extension Authors extension version: 2.0.1
-   Python package dependencies:

```json
N/A
```

Failed to launch kernel.
Error: No kernel specs selected
Error: No kernel specs selected
    at vi.launch (/Users/###/.vscode-insiders/extensions/ms-toolsai.datawrangler-0.25.3/out/extension.js:2:1959321)
    at mi.launchSession (/Users/###/.vscode-insiders/extensions/ms-toolsai.datawrangler-0.25.3/out/extension.js:2:1948312)

Extension version: 0.25.3
VS Code version: Code - Insiders 1.87.0-insider (9db1b0571e119289a2264971bdac75793965e063, 2024-02-07T05:48:10.997Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
pydisww1:30959800
8082a590:30958345
edj9j583:30943796
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp2r6:30958154

```

</details>

**Comment by epicwhale** [comment]
<img width="1000" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/670655/27b76893-025d-4884-a88c-ed722f3ac694">

When selecting hte Connect using local Python interpreter... this box appears

<img width="739" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/670655/93546e89-dab1-48cc-b242-d0f61fc85dec">

**Comment by pwang347** [comment]
Hi @epicwhale, thanks for reporting this issue!

I can confirm that this repros for me on any Jupyter pre-release versions >= `v2024.2.2024020201`. As a temporary workaround, could you please switch to the stable version (`v2024.1.1`) or an pre-release (`v2024.1.2024012502`) version while we look for a fix there?

**Comment by epicwhale** [comment]
@pwang347 I switched to stable (v0.24.0) from pre-release, but I'm still facing the same issue - how were you able to get out of this state?

**Comment by pwang347** [comment]
@epicwhale To clarify, the issue is due to a contract changing in the pre-release version of the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter). You will need to switch to stable for that extension but not Data Wrangler. Hope that helps!

**Comment by pwang347** [comment]
Note that we have a patch on our side to address this and it is scheduled to ship tomorrow.

**Comment by epicwhale** [comment]
@pwang347 amazing, thanks a ton, and for the update! would you know how long it generally takes to reach the pre-release version as an extension update?
