### ISSUE TITLE
copilot - not working

### ISSUE THREAD

**Issue by AmosG** [microsoft/vscode-data-wrangler#134]
Type: <b>Bug</b>

# Behaviour
when trying to type in the custom operation copilot wont start
## Expected vs. Actual
when typing copilot should send a requst and provide suggestion
XXX

## Steps to reproduce:

1. try to type anything in the custom operation

# Diagnostic data

-   Jupyter extension version: 2024.1.1
-   Python extension version: 2024.0.1
-   .NET Install Tool for Extension Authors extension version: 2.0.1
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.1.4",
    "pyarrow": "14.0.2"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

Extension version: 0.24.1
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (7.46GB free)|
|Process Argv|--crash-reporter-id 15155c55-d8f6-4387-9955-a2ead069fb67 --crash-reporter-id 15155c55-d8f6-4387-9955-a2ead069fb67 --crash-reporter-id 15155c55-d8f6-4387-9955-a2ead069fb67|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|Memory (System)|15.46GB (10.03GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
b5d27386:30958190
3ef8e399:30949928
e3gdj431:30958358

```

</details>

**Comment by pwang347** [comment]
Hi @AmosG! Thanks for opening this issue.

Currently this is expected as we are running our editor in a webview, so we don't have access to native VS Code features. If you are interested in seeing this in Data Wrangler, please upvote this issue: https://github.com/microsoft/vscode/issues/196705

Hope this helps!
