### ISSUE TITLE
Precision lost when inspect a dataframe with nano second value

### ISSUE THREAD

**Issue by Molin-L** [microsoft/vscode-data-wrangler#139]
## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): v0.26.0
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

Keep the original value.

## Actual behaviour

Set the last 2 digits to 0.

## Steps to reproduce:

When I inspected a dataframe which stores nano second value, Data Wrangler will set the last 2 digits to 0:

```
1708480568831982966 -> 1708480568831982900
```

![image](https://github.com/microsoft/vscode-data-wrangler/assets/25400909/19783842-71d0-40d6-93b1-ba4f01da6917)

**Comment by pwang347** [comment]
Hi @Molin-L, thanks for reporting this issue! We'll investigate it and provide updates here.
