### ISSUE TITLE
not showing data

### ISSUE THREAD

**Issue by mohomayoun** [microsoft/vscode-data-wrangler#141]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.2.0
-   Python extension version: 2024.0.1
-   .NET Install Tool for Extension Authors extension version: 2.0.2
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.0.3"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

Extension version: 0.26.0
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by pwang347** [comment]
Hi @mohomayoun, thanks for opening this issue. Could you please share a small example dataset that reproduces this issue? Thanks!

**Comment by Abebe-Gasparini** [comment]
I am facing a similar issue.
It seems a though the extension fails to automatically connect with the python kernel (3.12.2, in my case), and as a consequence it restarts all the terminals in vs code. If jupyter notebooks are open, the operation also results in deleting the variables in the related jupyter notebook. 

This is the data on the telemetry:
[
  {
    "name": "Activate",
    "properties": {
      "WranglerHost": "vscode",
      "configurations": "{\"dataWrangler.debug\":true,\"dataWrangler.enabledFileTypes\":{\"csv\":true,\"tsv\":true,\"parquet\":true,\"xlsx\":true,\"xls\":true},\"dataWrangler.startInEditModeForNotebookEntrypoints\":false,\"dataWrangler.useRelativePath\":false,\"dataWrangler.viewPastCodeSteps\":\"enabledWithData\",\"dataWrangler.experiments.allowPreviewingAllTheCode\":true,\"dataWrangler.experiments.autoDetectCsvDelimiter\":true,\"dataWrangler.experiments.byExampleOperations\":true,\"dataWrangler.experiments.customOperations\":true,\"dataWrangler.experiments.editLastAppliedOperation\":true,\"dataWrangler.experiments.fastCsvParsing\":true,\"dataWrangler.experiments.parquetExport\":true,\"dataWrangler.experiments.useJupyterProposedAPI\":false}"
    },
    "measurements": {
      "duration": 0.019
    }
  },
  {
    "name": "ActivateJupyter",
    "properties": {
      "WranglerHost": "vscode",
      "jupyterExtensionVersion": "2024.2.0",
      "pythonExtensionVersion": "2024.2.1"
    },
    "measurements": {
      "duration": 0.717
    }
  },
  {
    "name": "GetJupyterKernelService",
    "properties": {
      "WranglerHost": "vscode"
    },
    "measurements": {
      "duration": 0.14
    }
  },
  {
    "name": "LaunchDataWrangler",
    "properties": {
      "WranglerHost": "vscode",
      "entryPoint": "Walkthrough",
      "format": "csv",
      "viewMode": "dataWrangler"
    }
  }
]

When I try the walkthrough.csv tutorial, i am asked to select a connection runtime (in my case, I choose python 3.12.2) and everything works as expected.

However, whenever i try to start data wrangler to analyse my csv file, it fails leading to the issues described above.

I even tried to reinstall vs code, disable the other extensions and update the relevant python librqaries with pip to no avail.
![Picture1](https://github.com/microsoft/vscode-data-wrangler/assets/77531512/3baecdbe-64cf-4f19-9377-17608a81b2a5)
![Picture2](https://github.com/microsoft/vscode-data-wrangler/assets/77531512/9192ecbb-c270-416a-a733-27fcf7679e39)
![Picture3](https://github.com/microsoft/vscode-data-wrangler/assets/77531512/ca4afe7f-bee5-4117-9ea7-690291ae8137)
![Picture4](https://github.com/microsoft/vscode-data-wrangler/assets/77531512/bd34f1ec-0f84-4efc-a93b-c7d0cbada8e4)

**Comment by pwang347** [comment]
Hi @Abebe-Gasparini! Thanks for providing the details above.

I had a few more followup questions:
- Which version of Data Wrangler are you using? Does downgrading the version resolve the issue? If not, could you also try downgrading the Jupyter extension version as well?
- Does this issue happen in Jupyter notebooks as well?

If this issue only happens with that specific CSV file, could you also share the output from console? Ie. From the top menu bar Help > Toggle Developer Tools and then click the console icon.

Thanks!

**Comment by pwang347** [comment]
@mohomayoun It's my pleasure, and glad to hear that the issue was resolved! It seems like it may have been something transient related to the Python/OS environment if it is also affecting the Jupyter Notebook.

Will close the issue for now, but please feel free to reopen if there are any new followups.

Cheers!
