### ISSUE TITLE
Can't load saved file

### ISSUE THREAD

**Issue by peter-bbai** [microsoft/vscode-data-wrangler#149]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual
Open parquet file

vs 

Failed to update data frame: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Steps to reproduce:

df = df.groupby("Column").agg(set).reset_index()

save file to parquet

# Diagnostic data

-   Jupyter extension version: 2024.2.0
-   Python extension version: 2024.2.1
-   .NET Install Tool for Extension Authors extension version: 2.0.2
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.1",
    "pyarrow": "15.0.0"
  },
  "required": {
    "pandas": "1.1.0",
    "pyarrow": "0.0.1"
  },
  "unsatisfied": []
}
```

Extension version: 0.28.0
VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|. --crash-reporter-id a1d9092a-0f52-402a-aad5-591e8daad6d0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
8f97e687:30977000
ccp2r6:30958158
dsvsc020:30976470

```

</details>

**Comment by pwang347** [comment]
Hi @peter-bbai, thanks for opening this issue! It seems like this is related to https://github.com/microsoft/vscode-data-wrangler/issues/118. Could you please try updating Data Wrangler to 0.29.0 by installing the latest pre-release version?

**Comment by peter-bbai** [comment]
The error seems to go away with v 0.29.2. Thank you
