### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by sasa5linkar** [microsoft/vscode-data-wrangler#150]
If your project is to be used in a research paper do you have preferred citation?

**Comment by jmew** [comment]
Hi @sasa5linkar, thank you for your interest in Data Wrangler! For the citation, please just refer and point to our repo [https://github.com/microsoft/vscode-data-wrangler](https://github.com/microsoft/vscode-data-wrangler). When the paper is published, it would be great if you could link it here in this thread.

**Comment by pwang347** [comment]
Closing as the question has been answered. Cheers!
