### ISSUE TITLE
New Column by Example, No pattern detected on simple pattern

### ISSUE THREAD

**Issue by robinhalabicki** [microsoft/vscode-data-wrangler#151]
## Environment data

-   VS Code version: 1.87.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.28
-   Jupyter Extension version (available under the Extensions sidebar): v2024.2.0
-   Python Extension version (available under the Extensions sidebar): 3.10.12
-   OS (Windows | Mac | Linux distro) and version: Windows running VS Code in Linux WSL

## Expected behaviour
convert 
-$5,160.65
using example
-5160.65

## Actual behaviour

Error, no pattern exists

## Steps to reproduce:

![image](https://github.com/microsoft/vscode-data-wrangler/assets/22157886/db645563-b0d6-489e-bcbf-a664ed070daa)

**Comment by robinhalabicki** [comment]
This is the code it generated
`df.insert(6, "cf", df.apply(lambda row : row["cashflow"].split("$")[0] + row["cashflow"][row["cashflow"].find("$") + 1:row["cashflow"].find(".")], axis=1))`

when it should have done
df.insert(6, "cf", df.apply(lambda row : row["cashflow"].split("$")[0] + row["cashflow"][row["cashflow"].find("$") + 1:len(row["cashflow"])], axis=1))

**Comment by kycutler** [comment]
Hi @robinhalabicki, thanks for opening this issue!

I'm having trouble reproducing the issue on my end -- would you be able to share a sample dataset that triggers it? It is possible there may be some values further down in the column that are interfering with the pattern detection.

**Comment by robinhalabicki** [comment]
[Cashflow Categorization C.csv](https://github.com/microsoft/vscode-data-wrangler/files/14636749/Cashflow.Categorization.C.csv)
if you remove the comma before attempting the Column by example it handles it better

**Comment by kycutler** [comment]
Thank you for sharing the dataset! It's extremely helpful. We've identified the issue and are investigating how to fix. I'll keep this thread updated with any progress.

**Comment by kycutler** [comment]
Hi @robinhalabicki, the issue should now be fixed in the latest pre-release version of Data Wrangler. Please give it a try and feel free to re-open this issue if it persists.

Thanks for trying Data Wrangler!
