### ISSUE TITLE
Hotel_data

### ISSUE THREAD

**Issue by iamAntimPal** [microsoft/vscode-data-wrangler#152]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.2.0
-   Python extension version: 2024.2.1
-   .NET Install Tool for Extension Authors extension version: 2.0.2
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "1.5.3"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

Extension version: 0.28.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.73GB free)|
|Process Argv|--crash-reporter-id 9758dd57-4c7e-4146-bc8f-2b7d8a956038|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30991133
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30958158
dsvsc020:30976470
pythonaic:30992952

```

</details>

**Comment by kycutler** [comment]
Hi @iamAntimPal, thanks for opening this issue! If possible, could you please share more details about the problem, such as an error message or screenshot, and a small sample dataset for us to reproduce the issue?

**Comment by pwang347** [comment]
Closing the issue due to inactivity. Please feel free to reopen if needed, thanks!
