### ISSUE TITLE
Load GeoDataFrame parquet: `Failed to update data frame: Unterminated UTF-8 sequence when encoding string`

### ISSUE THREAD

**Issue by turbotimon** [microsoft/vscode-data-wrangler#153]
## Environment data

-   VS Code version: 1.85.2
-   Data Wrangler Extension version (available under the Extensions sidebar): v0.29.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1100101639
-   Python Extension version (available under the Extensions sidebar): v2024.2.1
-   OS (Windows | Mac | Linux distro) and version: nixOS 23.11
-   Pandas version: 2.0.0
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

The extension can open the parquet file and shows the geometry as a string (eg. `b'\x01\x06\x00\...`) like pandas does. Although you cannot see the geometry in this way, you can still see other information in other columns next to the geometry.

## Actual behaviour

Error: Failed to load data / Failed to update data frame: Unterminated UTF-8 sequence when encoding string

## Steps to reproduce:

1. Create a GeoDataFrame and save it as parquet:
```python
import pandas as pd
import geopandas as gpd
from shapely.geometry import MultiPolygon

polygon = MultiPolygon([[[(-1, -1), (-1, 1), (1, 1), (1, -1), (-1, -1)]]])
data = {'geometry': [polygon]}
gdf = gpd.GeoDataFrame(data, crs='EPSG:4326')

gdf.to_parquet("geodataframe.parquet")
pd.read_parquet("geodataframe.parquet") # This works fine, but the extension can not open it
#                                             geometry
# 0  b'\x01\x06\x00\x00\x00\x01\x00\x00\x00\x01\x03...
```
2. Open the parquet file with DataWrangler extension

## Logs

Notification:
```
Source: Data Wrangler (Preview) (Extension)
Failed to update data frame: Unterminated UTF-8 sequence when encoding string
```

**Comment by kycutler** [comment]
Hi @turbotimon, this issue should now be fixed in the latest pre-release version of Data Wrangler. Please give it a try and feel free to re-open this issue if it persists.

Thanks for trying Data Wrangler!

**Comment by turbotimon** [comment]
@pwang347 nice thanks! I can confirm it work with v1.0.1
