### ISSUE TITLE
Loading Polars Dataframe Error

### ISSUE THREAD

**Issue by guocity** [microsoft/vscode-data-wrangler#160]
## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

Loading Polars Dataframe

## Actual behaviour

Expected df to be a DataFrame, but got: <class 'polars.dataframe.frame.DataFrame'>

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by realseqi** [comment]
same with me

**Comment by Vitorbnc** [comment]
Could you support polars? It would be very useful

**Comment by kycutler** [comment]
Hi folks, good news! Loading Polars `DataFrame` and `Series` data is now supported in the latest pre-release version of Data Wrangler. Please give it a try and feel free to re-open this issue if the error persists.

Also note that when loading the data, Data Wrangler converts it to a pandas DataFrame for applying operations & code generation. If this is something you would like to see changed, please open a separate issue.

Thanks for trying Data Wrangler!

**Comment by pabloRRosales** [comment]
Hello, Data Wrangler actually helped me figure out (potentially) why I was unable to open my polars dataframes; attempting to use Data Wrangler raised a pyarrow requirement error. once I pip installed pyarrow I was able to open my df in the default data viewer as well as DW!

**Comment by marcmk6** [comment]
this is weird. I'm using the pre-release version but it still failed to load polars df 
```
Expected df to be a DataFrame, but got: <class 'polars.dataframe.frame.DataFrame'>
```

**Comment by HernandoR** [comment]
hi @pwang347! I wonder if we can support pl.dataframe viewing for debug variables?
