### ISSUE TITLE
cannot view datasets from sklearn library

### ISSUE THREAD

**Issue by Shaka42** [microsoft/vscode-data-wrangler#164]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.3.1
-   Python extension version: 2024.4.1
-   .NET Install Tool for Extension Authors extension version: 2.0.3
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

Extension version: 0.28.0
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.77GB (0.37GB free)|
|Process Argv|--crash-reporter-id 0358cc8b-f9b9-45fa-8fbd-16fd2742e396|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideot:31016892
dsvsc021:30996838
gd77d436:30999572
g316j359:31013175

```

</details>

**Comment by pwang347** [comment]
Hi @Shaka42, thanks for opening this issue! If possible, could you please provide a sample dataset or code for me to help investigate? Thank you!

**Comment by Shaka42** [comment]
Thank you for your response but the issue was not my part I had used it poorly

**Comment by pwang347** [comment]
No problem! Thanks for confirming, I'll go ahead and close the issue then.
