### ISSUE TITLE
Publish data-wrangler to Open VSX

### ISSUE THREAD

**Issue by roxane-data** [microsoft/vscode-data-wrangler#165]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by pwang347** [comment]
Hi @roxane-data, thank you for opening this issue. I discussed this with the team and unfortunately this is not something we plan to support at the moment, since this means we would need to be prepared to support users from all derivative IDEs. Note that we are currently moving fast and making various integrations; as a result we cannot make such guarantees. For a similar answer please see https://github.com/microsoft/vscode-python/issues/17173#issuecomment-956875871.

If anything changes, I will reopen this issue and let you know. Thank you!

**Comment by ChristofKaufmann** [comment]
@pwang347 I do understand this, but vscode-python has got an MIT license, while vscode-data-wrangler has got a VS Marketplace license (?). So, to my understanding, it is not possible that the community can handle the user support for derived IDEs. Or is it?
For such an important extension, especially now that the Jupyter DataViewer got [deprecated](https://github.com/microsoft/vscode-jupyter/issues/15486), there should something available for derived IDEs. As an example: We use code-server on a JupyterHub on our University cluster and there will be an exam in September. With no alternative to view DataFrames in memory, I won't update code-server to 1.92.

**Comment by ChristofKaufmann** [comment]
I was frustrated about the situation. So I developed and released a data viewer called "DataFrame Viewer" ([Open VSX Registry](https://open-vsx.org/extension/ChristofKaufmann/dataframe-viewer), [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=ChristofKaufmann.dataframe-viewer)). In contrast to DataWrangler, it's a pure viewer (not an editor or code generator), but it has some unique features:

- can be installed on a JupyterHub code-server instance (Open VSX Registry) 🥳 
- values can be colorized similar to a heatmap (inspired by Spyder IDE)
- the filter is more powerful than in DataWrangler (full pandas query power)
- multi-key sorting
- percentage of missing values visualized as bars
- data distribution plots

Have a look at the store page for screen shots and videos.
