### ISSUE TITLE
DateTime datatype is always read as object datatype instead, even if we change the datatype and save it, its still read as object type

### ISSUE THREAD

**Issue by Blazekiller8** [microsoft/vscode-data-wrangler#169]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

Columns of datetime type as taken as object type instead

## Steps to reproduce:

1. Open a csv file with a column of datetime datatype
2. I will show its type as Object instead
3. Manually change the type to datetime and export the file as csv
4. When opening the updated csv file, it will still show that column as object type as default

# Diagnostic data

-   Jupyter extension version: 2024.4.0
-   Python extension version: 2024.6.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2",
    "pyarrow": "16.0.0"
  },
  "required": {
    "pandas": "1.4.0",
    "pyarrow": "0.0.1"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Reopen
-   Active mode: dataWrangler

Extension version: 1.0.0
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (1.38GB free)|
|Process Argv|--crash-reporter-id d9f1f488-f4fe-4b19-a2b0-a1049a6079da|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790
fchga941:31038042
dwnewjupytercf:31035177

```

</details>

**Comment by pwang347** [comment]
Hi @Blazekiller8, thank you for opening this issue and for trying Data Wrangler! Note that the CSV format does not typically preserve data types (it only stores the text version of the values). So if you would like to reopen Data Wrangler with the same types that you had previously, I would recommend saving and loading using `.parquet` instead.

Regarding the default conversion to `object` type, this is also currently as designed given that Pandas treats the dates in the CSV as strings by default. That being said, we are planning to take a look at exposing more options and better defaults during the import process to the user and we've noted down your feedback in this area.

Thanks again!
