### ISSUE TITLE
Data viewer for debugged Interactive python cell doesn't open while at a breakpoint

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-data-wrangler#173]
1. with jupyter extension pre-release installed, create a python file with contents:

```
# %%
import pandas as pd

# create a sample dataframe
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Gender": ["F", "M", "M"],
}
df = pd.DataFrame(data)
df
```

2. set a breakpoint on the last line and click the debug Cell code lens
3. open the jupyter variable view and click the button to open the data viewer
:bug: nothing happens, but the data viewer will open when the debugger continues

**Comment by pwang347** [comment]
Fixed in pre-release 1.1.1. Thanks @amunger!
