### ISSUE TITLE
Can you add support for jsonl files?

### ISSUE THREAD

**Issue by KrisTC** [microsoft/vscode-data-wrangler#177]
This tool looks really useful. But I am working with jsonl files like those on huggingface.
It would be very nice if this extension worked with jsonl files.
Example: https://huggingface.co/datasets/Abirate/english_quotes/blob/main/quotes.jsonl 

Thanks

**Comment by ehartford** [comment]
Please add support for jsonl

**Comment by pwang347** [comment]
Hi @KrisTC @ehartford, great news! We've just added support for JSONL files in pre-release 1.9.1. It currently requires enabling a feature flag as seen in the image below:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/d7f2073c-e0e9-459e-8f1a-a34191f3e43c">

We would love if you could give it a try and let us know if you have any feedback.
Thanks!

**Comment by ehartford** [comment]
Awesome I'll try it now

**Comment by ehartford** [comment]
I update to 1.9.1 pre-release, and I reset vscode.

i try to select JSON Lines

I see this

<img width="1157" alt="image" src="https://github.com/user-attachments/assets/a21ea444-fa3b-435d-a534-4d551e61e923">

**Comment by ehartford** [comment]
false alarm; I reset again and JSONL appears

**Comment by KrisTC** [comment]
Thank you. Works great
