### ISSUE TITLE
Support for Jupyter-like code cells

### ISSUE THREAD

**Issue by jannisko** [microsoft/vscode-data-wrangler#18]
VSCode supports the interactive use of plain `.py` files using the special `#%%` comment: https://code.visualstudio.com/docs/python/jupyter-support-py
This keeps your file easily executable, more readable as plaintext, and excludes any results/charts. The results of the executed cells are then shown in the [python interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py#_using-the-python-interactive-window). Data Wrangler currently doesn't seem to pick up on dataframes being displayed in this window, making it incompatible with this type of notebook.

Could this feature be part of the scope of the extension in the future?

Thanks a lot!

**Comment by pwang347** [comment]
Thanks for making the request @jannisko!

Before we can make this change, we'll need an API exposed from the Jupyter extension in order for this to work. I've opened an issue here https://github.com/microsoft/vscode-jupyter/issues/13130 to track this.

**Comment by yinghawl** [comment]
Any more progress on this issue. This will be a very helpful feature. Is there a way to hack around?

**Comment by jabbera** [comment]
@yinghawl I think it's dead as the jupyter maintainer don't be implementing the required feature: https://github.com/microsoft/vscode-jupyter/issues/13130

**Comment by pwang347** [comment]
@yinghawl @jabbera FYI I'm trying to bring up the discussion again here: https://github.com/microsoft/vscode-jupyter/issues/15196

We have some shared scenarios now where this makes sense so I'm looking to revive the ask again. Cheers!

**Comment by pwang347** [comment]
Feel free to chime in at https://github.com/microsoft/vscode-data-wrangler/issues/140!

**Comment by pwang347** [comment]
Closing as resolved with https://github.com/microsoft/vscode-data-wrangler/issues/140
