### ISSUE TITLE
Feature Request: Toggle Cleaning Steps

### ISSUE THREAD

**Issue by attilam** [microsoft/vscode-data-wrangler#180]
Type: <b>Feature Request</b>

# Behaviour

## Expected vs. Actual

The non-destructive nature of the Cleaning Steps stack is fantastic! Walking back and forth in the history of operations is very powerful. It would be cool if it was possible to skip some of them. E.g. on each step there was a "visibility" flag that toggled if the step is applied, or not. Similarly to how modifiers can be toggled on/off in Blender.

For example this would make it possible to play with different settings of an operation without having to add/remove it, or change the script code, especially if we need other steps to be performed afterwards.

Hm, reordering, and inserting steps would be handy for this too... 🤔

## Steps to reproduce:

N/A

# Diagnostic data

-   Jupyter extension version: 2024.4.0
-   Python extension version: 2024.6.0
-   .NET Install Tool for Extension Authors extension version: 2.0.5
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.1"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.0.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by pwang347** [comment]
Hi @attilam, thanks for opening this request! I've merged your comments into another issue for better tracking improvements to the cleaning steps: https://github.com/microsoft/vscode-data-wrangler/issues/62

Feel free to chime in more in that thread. Cheers!
