### ISSUE TITLE
UNC Server paths get backslashes double-escaped which causes loading failure

### ISSUE THREAD

**Issue by WillFeavyour** [microsoft/vscode-data-wrangler#183]
## Environment data

-   VS Code version: 1.89.1
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.0.2
-   Jupyter Extension version (available under the Extensions sidebar): 2024.4.0
-   Python Extension version (available under the Extensions sidebar): 2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Pandas version: 2.2.2
-   Python and/or Anaconda version: 3.12.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

Right clicking on a file on a network drive in the Explorer pane and clicking "Open in Data Wrangler" should open a file in Data Wrangler tab.

## Actual behaviour

Backslashes are double-escaped and the file fails to load. Manually removing the double slashes in the Data Wrangler command prompt lets the file load successfully. This works fine for files in a local directory such as the Desktop, but not a network drive with a UNC path.

## Steps to reproduce:

1. Add folder to VSCode workspace which is on a network drive, e.g. `\\myserver.net\data`
2. Try and open the file in Data Wrangler using the context menu
3. The Data Wrangler prompt shows the file path with slashes double-escaped, and the error message has them quad-escaped:
![image](https://github.com/microsoft/vscode-data-wrangler/assets/17527199/85c05750-91a8-4723-8b45-bb4939b5d13d)

4. Manually editing the `pd.read_csv` line to have the correct backslashes (not escaped) lets the file load.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
14:31:27.931 [info] Interrupting kernel via custom event (Win32)
14:31:27.931 [info] Interrupting kernel via custom event (Win32)
```

</p>
</details>

**Comment by kycutler** [comment]
Hi @WillFeavyour, thanks for opening this issue! This is now fixed in the latest pre-release version of Data Wrangler (1.3.0). You can install the pre-release version by selecting Data Wrangler from the extensions panel in VS Code and clicking "Switch to Pre-Release Version", then "Restart Extensions" after the update. 

Please give it a try and feel free to re-open this issue if the problem persists. Thanks for trying Data Wrangler!
