### ISSUE TITLE
VS Code Data Wrangler Extension 

### ISSUE THREAD

**Issue by Murtada-Khalafalla** [microsoft/vscode-data-wrangler#184]
## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @Murtada-Khalafalla, thanks for opening the issue! Could you please share more information on what wasn't working for you, and how I could try to reproduce it?

**Comment by pwang347** [comment]
Closing this issue for now due to inactivity. Please feel free to reopen and provide more details!
