### ISSUE TITLE
Web version: Not allowed to load local resource: file://

### ISSUE THREAD

**Issue by TsubasaBE** [microsoft/vscode-data-wrangler#186]
## Environment data

-   VS Code version: 1.89.1 (Web version)
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.1.2 (pre-release)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Linux
-   Pandas version: 2.1.4
-   Python and/or Anaconda version: 3.10.14
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A (Docker, packages installed in user home)

## Expected behaviour

Using the web version of VSCode (code serve-web), when trying to open a pandas dataframe in data wrangler, a new data wrangler view should be opened in a new tab and the view should be rendered.

## Actual behaviour

Using the web version of VSCode (code serve-web), when trying to open a pandas dataframe in data wrangler, a new data wrangler view opens in a new tab, but the view itself isn't rendered.
Using Chrome developer tools, the following errors are shown in the console:
`index.html:1026 Not allowed to load local resource: file:///home/jupyter/.vscode-server/extensions/ms-toolsai.datawrangler-1.1.2/out/***`
![image](https://github.com/microsoft/vscode-data-wrangler/assets/6402607/042a868e-da9b-4f4b-a55e-872cc40bb6e7)

Data wrangler works correctly using the desktop version of VSCode.

## Steps to reproduce:

1. Start web version of code:
  `code serve-web`
2. Install jupyter, python and data wrangler extensions.
3. Run some Python code using pandas dataframes.
4. Open a dataframe in a data wrangler view.

![image](https://github.com/microsoft/vscode-data-wrangler/assets/6402607/1e244020-678f-4245-a6f0-0e8d1db780ce)
![image](https://github.com/microsoft/vscode-data-wrangler/assets/6402607/106ce21a-c006-4627-9d5a-d2b8e1ff577d)
![image](https://github.com/microsoft/vscode-data-wrangler/assets/6402607/042a868e-da9b-4f4b-a55e-872cc40bb6e7)

## Logs

<details>

<summary>
N/A
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @TsubasaBE, thanks for reporting the issue! I've merged a fix for it and will update this issue for when it is released. Cheers!

**Comment by TsubasaBE** [comment]
Hi @pwang347 ,

Thanks very much for your quick fix. Appreciate it.

Thank you again.

**Comment by pwang347** [comment]
Hi @TsubasaBE, this issue should now be fixed in pre-release version 1.3.0. Thanks again for reporting the issue and for using Data Wrangler!

**Comment by TsubasaBE** [comment]
Hi @pwang347 ,

Yes. It's working in the pre-release version now.

![image](https://github.com/microsoft/vscode-data-wrangler/assets/6402607/b7dde057-ee49-43b0-b132-5163d4f7a981)

Thank you very much for the fix. I'm really loving the extension.

Thank you again.
