### ISSUE TITLE
Missing packages message when trying to open data viewer

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-data-wrangler#191]
I'm in a venv with just pandas installed.

![Data Wrangler opens to an error screen](https://github.com/microsoft/vscode-jupyter/assets/7199958/b4298343-7672-490d-b635-4ad95cf11a2d)

_Originally posted by @rzhao271 in https://github.com/microsoft/vscode-jupyter/issues/15680#issuecomment-2136200174_

**Comment by amunger** [comment]
Maybe there was some dependencies that Jupyter was taking care of installing?

**Comment by amunger** [comment]
@rzhao271 - if you disable the data wrangler extension, does the Data viewer from Jupyter open successfully?

**Comment by pwang347** [comment]
@amunger @rzhao271 Thank you for reporting this issue! It seems like we had a dependency on setuptools which is [no longer installed by default with venv and ensurepip](https://github.com/python/cpython/pull/101039). We can fix this on our side by removing our dependency on it.
