### ISSUE TITLE
Python interpreter selection error

### ISSUE THREAD

**Issue by bhuffman-usgs** [microsoft/vscode-data-wrangler#195]
Type: <b>Bug</b>

# Behavior

## Expected vs. Actual

I expected to be able to select the python interpreter I want to use but I receive an error for not having a jupyter extension.

## Steps to reproduce:

1. Install Data Wrangler extension
2. Right click a csv and "Open in Data Wrangler"
3. Click "Connect to runtime" and select Python Interpreter.
4. Receive error notification in bottom right "Failed to launch kernel.  Error: Could not get Jupyter extension...."

# Diagnostic data

-   Jupyter extension version: Not installed
-   Python extension version: 2024.6.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
N/A
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.3.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.20GB (46.99GB free)|
|Process Argv|C:\\APPS\\eden --crash-reporter-id c09b9c96-87e8-451c-aa72-ca6ee177f106|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by bhuffman-usgs** [comment]
Below is the error I receive.
![image](https://github.com/microsoft/vscode-data-wrangler/assets/40209416/77b333cf-a090-4bad-83d6-199b030cd469)
![image](https://github.com/microsoft/vscode-data-wrangler/assets/40209416/9abd8125-cf3e-4a7c-956f-452b794a1ddf)

**Comment by pwang347** [comment]
Hi @bhuffman-usgs, thank you for opening this issue!

It looks like you don't have the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) installed, which is needed for the local Python kernel feature. Could you please install the extension and try again?

**Comment by bhuffman-usgs** [comment]
Sure thing, I’ll add that.  I’d suggest that the dependency be listed on the extensions landing page under the setup.

Brad
________________________________
From: Paul ***@***.***>
Sent: Friday, May 31, 2024 2:42:02 PM
To: microsoft/vscode-data-wrangler ***@***.***>
Cc: Huffman, Bradley J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-data-wrangler] Python interpreter selection error (Issue #195)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bhuffman-usgs<https://github.com/bhuffman-usgs>, thank you for opening this issue!

It looks like you don't have the Jupyter extension<https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter> installed, which is needed for the local Python kernel feature. Could you please install the extension and try again?

**Comment by pwang347** [comment]
Appreciate the suggestion, we'll take a look at improving the docs to add more info there so it's more clear! Just to confirm also, did you get a popup asking you to install the Jupyter extension? Should look something like this:

<img width="559" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/8560030/4967dba6-c39b-4618-b421-32d8115f530e">

**Comment by bhuffman-usgs** [comment]
Sorry Paul, I forgot to respond.  No, when I added the extension there was no pop-up asking me to install a Jupyter extension.

**Comment by pwang347** [comment]
Hey! No worries at all. The popup should only appear when you click on step 2 in the image you have here:
![image](https://github.com/microsoft/vscode-data-wrangler/assets/8560030/e9b60ac6-7922-40d9-89f9-27dece37563d)

If you don't mind trying again, could you please uninstall the Jupyter extension again and run this command (using `ctrl+shift+P` to open the command palette) before opening a CSV file?

<img width="612" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/8560030/89166765-dae4-4147-bb09-48abad92a7a4">

Thanks!

**Comment by mschossler** [comment]
![Screenshot from 2024-07-08 20-36-06](https://github.com/microsoft/vscode-data-wrangler/assets/84537230/fd3f612f-21da-447a-8c5e-a1870cbfb7d7)

Hi, I'm having a similar issue. But I have Jupyter installed, and after clicking to install the extension again, this box never goes away, and the extension never works.

**Comment by pwang347** [comment]
Hi @mschossler! Could you also check to see if you have the Python extension installed already? You will need to have both Python and Jupyter extensions installed as mentioned in the README section here: https://github.com/microsoft/vscode-data-wrangler?tab=readme-ov-file#set-up-your-environment

We're using the built-in VS Code API to install extensions, so if that isn't working you might want to try directly from the VS Code marketplace. Thanks!

**Comment by mschossler** [comment]
Hi, Yes. I have already uninstalled Python and Jupyter extensions, cleaned the cache of the data wrangler, and installed Jupyter and Python again. I still have the same issue.

**Comment by pwang347** [comment]
Got it, thanks for giving that a try. Does this discussion apply to you by any chance?
https://github.com/microsoft/vscode-data-wrangler/issues/129

Extensions could also fail to resolve if they live on different host instances, which this setting can cause. Let me know if this resolves the issue for you!

**Comment by mschossler** [comment]
Hi, Thank you! 

Following the discussion of the other issue, I deleted this using the UI:

"extensions.experimental.affinity": {
        "ms-toolsai.jupyter": 2,
        "ms-toolsai.jupyter-renderers": 2,
        "ms-python.python": 2,
        "ms-python.vscode-pylance": 2
}

Restarted vscode, and voila.
