### ISSUE TITLE
Unable to read data stored in cuda when debugging

### ISSUE THREAD

**Issue by ITOTI-Y** [microsoft/vscode-data-wrangler#201]
## Environment data

-   VS Code version: v1.90.0
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.2.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.8.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11 23H2-WSL Ubuntu-22.04
-   Pandas version: 2.2.2
-   Python and/or Anaconda version: 3.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

Ability to view values in the data viewer when debugging.

## Actual behaviour

Unable to view when data is stored on cuda devices

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Course of action

![Code_13dmHXaLUp](https://github.com/microsoft/vscode-data-wrangler/assets/35416777/f7ac540f-b5a0-4be4-b635-1b42505b91db)

2. Error message

```
Incorrectly formatted content received: {"name": "TypeError", "message": "can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.", "stack": " File \"<string>\", line 51, in __DW_DEBUG_WRAPPER__\n File \"<string>\", line 94, in exec_isolated_code\n File \"<string>\", line 2, in <module>\n"}
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.90.0, wsl, desktop)
Jupyter Extension Version: 2024.5.0.
Python Extension Version: 2024.8.0.
Pylance Extension Version: 2024.6.1.
Platform: linux (x64).
Workspace folder ~/code/Airflow-Reversal-Prediction, Home = /home/pan
```

</p>
</details>

**Comment by pwang347** [comment]
HI @ITOTI-Y, thanks for reporting this issue! We've merged a fix on our side in the latest pre-release version 1.3.1. It would be great if you could give it a try and let me know if the issue persists.
