### ISSUE TITLE
Bug when viewing dataframes having a mix of real and complex numbers

### ISSUE THREAD

**Issue by nabilkhalid56** [microsoft/vscode-data-wrangler#203]
I am looking for a data viewer that can also handle complex variables. Jupyter Notebook shows complex variables as [object], therefore, I just tried data wrangler pre-release in vscode Insider. Although I can see all the variables and their values, the viewer somehow shows the real numbers as complex numbers. Could this be fixed?

## Environment data

-   VS Code version: 1.91.0-insider
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.1.2 (pre-release)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.2024052401 (pre-release)
-   OS (Windows | Mac | Linux distro) and version: windows 11
-   Python and/or Anaconda version: 3.10.8

## Expected behaviour

when using a mix of real and complex numbers in a dataframe, the viewer should show columns with complex data as complex numbers and columns with real data as real.

## Actual behaviour

When using a mix of real and complex numbers in a dataframe, the viewer shows all columns as complex, even the ones that are real.

## Steps to reproduce:
```
import pandas as pd

# DataFrame with real numbers
df_real = pd.DataFrame({
    'A': [1.1, 2.2, 3.3],
    'B': [4.4, 5.5, 6.6],
    'C': [7.7, 8.8, 9.9]
})

# DataFrame with complex numbers
df_complex = pd.DataFrame({
    'A': [1+1j, 2+2j, 3+3j],
    'B': [4+4j, 5+5j, 6+6j],
    'C': [7+7j, 8+8j, 9+9j]
})

# DataFrame with complex numbers
df_real_complex = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4+4j, 5+5j, 6+6j],
    'C': [7+7j, 8+8j, 9+9j]
})

# DataFrame with a mix of real, complex, and strings
df_real_complex_string = pd.DataFrame({
    'A': ['baz', 'bar', 'foo'],
    'B': [4.4+0j, 9+9j, 5+5j],
    'C': [1, 2, 3]
})

print("DataFrame with real numbers: DataWrangler view looks GOOD")
print(df_real)
print("\nDataFrame with complex numbers:  DataWrangler view looks GOOD")
print(df_complex)
print("\nDataFrame with a mix of real, complex: DataWrangler view looks INCORRECT. ALL columns are shown as complex")
print(df_real_complex)
print("\nDataFrame with a mix of real, complex, and strings:  Surprisingly, DataWrangler view looks GOOD")
print(df_real_complex_string)
print("\nEND")
```
-->

## Logs

DataFrame with real numbers: DataWrangler view looks GOOD
     A    B    C
0  1.1  4.4  7.7
1  2.2  5.5  8.8
2  3.3  6.6  9.9

DataFrame with complex numbers:  DataWrangler view looks GOOD
          A         B         C
0  1.0+1.0j  4.0+4.0j  7.0+7.0j
1  2.0+2.0j  5.0+5.0j  8.0+8.0j
2  3.0+3.0j  6.0+6.0j  9.0+9.0j

DataFrame with a mix of real, complex: DataWrangler view looks INCORRECT. ALL columns are shown as complex
   A         B         C
0  1  4.0+4.0j  7.0+7.0j
1  2  5.0+5.0j  8.0+8.0j
2  3  6.0+6.0j  9.0+9.0j

DataFrame with a mix of real, complex, and strings:  Surprisingly, DataWrangler view looks GOOD
     A         B  C
0  baz  4.4+0.0j  1
1  bar  9.0+9.0j  2
2  foo  5.0+5.0j  3

<p>

</p>
</details>

![image](https://github.com/microsoft/vscode-data-wrangler/assets/35198306/af685e1e-f4a2-4c93-8328-2775aada9efc)

**Comment by kycutler** [comment]
Hi @nabilkhalid56, thank you for the detailed bug report! This is now fixed in the latest pre-release version of the Data Wrangler extension (1.5.0 and above). Please give it a try and feel free to re-open this issue if the problem persists.

Thanks for trying Data Wrangler!
