### ISSUE TITLE
Request: Shorter tab names

### ISSUE THREAD

**Issue by williaMorris** [microsoft/vscode-data-wrangler#205]
Hello,

Please may I request shorter, clearer tab names? 

Ever since switching from the Data Viewer of Jupyter to the Data Wrangler, I notice tabs have much longer names, especially in debug mode. I can only see two or three on the screen, and it is hard to distinguish between them because the filenames are such a small part of the tab name - there is a lot of duplicated text:

![image](https://github.com/microsoft/vscode-data-wrangler/assets/60658309/2267d385-0c02-46e4-81a0-40a976ecc9d1)

Many thanks in advance, and thanks also for the Data Wrangler itself.

**Comment by SamAuclair** [comment]
I second this.

**Comment by pwang347** [comment]
Hi @williaMorris, @SamAuclair - just wanted to give an update that we've merged a change to make the tab titles more compact (as well as a change to make the icon more colorful) in pre-release 1.5.2! Please feel free to give it a try and let us know if you have any more feedback. Thanks!

**Comment by williaMorris** [comment]
Thank you very much Paul, that's much better! I greatly appreciate it.
