### ISSUE TITLE
Feature Request: Option to adjust column spacing uniformly or to take transposition

### ISSUE THREAD

**Issue by wjfu99** [microsoft/vscode-data-wrangler#206]
# Description:
It would be extremely helpful to have the ability to adjust column spacing uniformly. Since sometimes, the column spacing seem a little too wide for watching a Tensor or Numpy array.
<img width="1227" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/57850011/baec56cd-34b5-4197-beae-0601b4a98d45">

# Current Use Case:
Under the same window size, the current column spacing can only display a few values. To see more values, users must drag a very small scrollbar to locate the desired values, and even a slight movement causes a large number of values to flash by quickly. The phenomenon is particularly severe for array with relatively long width and low height. ``Go to column`` seems a alternative solution to locate, but lower column spacing will lead to more information in a limited space.

# Expected Features:
Here are some feature requests that I think might be possible but are not necessarily correct:
* Provide an option for users to adjust the column spacing uniformly: <img width="1228" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/57850011/1a2e052d-b274-4dad-9da2-f7d80dd98055">
* or perhaps minimize the row spacing as much as possible when users choose to hide column insights.
* Provide an option similar to transposing a matrix, where columns become rows and rows become columns.

```[tasklist]
### Tasks
```

**Comment by pwang347** [comment]
Hi @wjfu99, thank you for the feature request and patience. Just wanted to share an update that it should now be possible to customize the default column width using the `Data Wrangler › Grid: Default Column Width` setting. You can find this in the latest pre-release version 1.15.1. Hope this helps!

@Sutyke I created a new issue here to track the automatic width feature separately: https://github.com/microsoft/vscode-data-wrangler/issues/357

**Comment by giomegreladze** [comment]
Hi, I’m experiencing the same issue.

While the recently implemented feature allows configuring a default column width, it does not solve the core problem. The Data Viewer still does not provide an option to automatically adjust column widths based on content.

Currently, when working with datasets columns are displayed with a fixed default width, Longer values are truncated and 
each column must be resized one by one, This process must be repeated every time a dataset is opened

This becomes especially frustrating when working frequently with tabular data. What would really help is an auto-adjust column width feature.
