### ISSUE TITLE
View pandas dataframe option for VSCode running ipython mode

### ISSUE THREAD

**Issue by ddjustina** [microsoft/vscode-data-wrangler#207]
## Environment data

-   VS Code version: 1.90.1
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.2.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.8.1
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Pandas version: 1.4.0
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

I use the [Python interactive window to work with Jupyter notebooks](https://code.visualstudio.com/docs/python/jupyter-support-py). When I first installed the extension, I was able to view loaded dataframes by going into the command palette and selecting the "View df" option, but it is no longer available.

## Actual behaviour

The option is no longer available. See the image attached.

![image](https://github.com/microsoft/vscode-data-wrangler/assets/7991816/a8f1e711-95f3-4efd-844b-605bcb19e24d)

## Steps to reproduce:

1. Open VS Code Command Palette.
2. Type "Data Wrangler".
3. Check the displayed suggestion.

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @ddjustina, thanks for opening this issue! This command wasn't supposed to appear previously as there were some more cases to address, but we've just now added official support for it as well as having a corresponding button in the toolbar. This is available in the latest pre-release 1.5.2 if you would like to try it out.

Cheers!
