### ISSUE TITLE
simplify installing required packages for opening data viewer

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-data-wrangler#211]
## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Steps to reproduce:

1. Create a fresh venv and select it for a notebook kernel
2. Install the `polars` package and Create a polars data frame

```
%pip install polars

import polars as pl

x = pl.DataFrame({"alpha": [1, 2, 3, 4], "beta": ["c", "u", "d", "m"]})
```

4. open the data viewer for the data frame from the jupyter variable viewer
error: `Failed to load the data frame: ModuleNotFoundError: No module named 'pandas'`
5. install pandas and retry
error: `Failed to load the data frame: ModuleNotFoundError: No module named 'pyarrow'`
6. install pyarrow and retry
success

It would be nice if this page included a button to install required packages (both pandas and pyarrow) and reload
![image](https://github.com/microsoft/vscode-data-wrangler/assets/2019016/ac0b5b83-5343-41b1-9e6b-eb677cbaebca)

**Comment by pwang347** [comment]
Hi @amunger, this is now fixed in the latest pre-release 1.5.0. Thanks for reporting the issue!
