### ISSUE TITLE
FEATURE REQUEST: Add configuration setting to optionally hide "column insights" by default

### ISSUE THREAD

**Issue by majode** [microsoft/vscode-data-wrangler#221]
The data wrangler is a significant improvement over the old data viewer. However, for the dataframes I work with, I almost NEVER need the column insights. I would rather use that vertical space for displaying more rows of data.

It would be really helpful to see a new configuration item in the settings to let me define the default behavior for a new data wrangler window. Something like "dataWrangler.columnInsights.displayOnOpen: false".

**Comment by pwang347** [comment]
Hi @majode, just wanted to let you know that this option is now available in latest pre-release version 1.7.2. Please give it a try and let me know what you think. Thanks!
