### ISSUE TITLE
Filter never works the first time

### ISSUE THREAD

**Issue by carlosgfl** [microsoft/vscode-data-wrangler#222]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

When I press the three dots at the top of the column to filter it. I click on Add filter, and when I click on the arrow in the dropdown menu "Select a condidion", the filter window closes itself. I need to click again a second time and that time it works.

## Steps to reproduce:

1. Click on the 3 dots on top of a column
2. Click on add filter
3. Click on Select a condition. (it breaks)

# Diagnostic data

-   Jupyter extension version: 2024.6.0
-   Python extension version: 2024.8.1
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "1.1.4",
    "pyarrow": "2.0.0"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.4.1
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (0.93GB free)|
|Process Argv|--crash-reporter-id 781067a8-6986-4314-9953-6665d8f64ec7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31082724

```

</details>

**Comment by pwang347** [comment]
Hi @carlosgfl! Thanks for reporting. We've identified the issue and have released a fix in both stable (v1.4.2+) and pre-release (v1.5.3+) channels for it. Please give the latest version a try and let me know if the issue is still occurring for you!

Adding a link to #216 as this appears to be the same issue.
