### ISSUE TITLE
loading for ever!!

### ISSUE THREAD

**Issue by running-machin** [microsoft/vscode-data-wrangler#223]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.6.2024062802
-   Python extension version: 2024.11.2024070801
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.5.2
VS Code version: Code - Insiders 1.92.0-insider (82104a3a6cf8713b81e5bbd97960dbf5c82a816a, 2024-07-05T00:00:00.000Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5980HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.41GB (16.54GB free)|
|Process Argv|--crash-reporter-id 6d5c45a4-0138-466c-8f50-ab80a22586af|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5980HS with Radeon Graphics (16 x 0)|
|Memory (System)|15.33GB (11.08GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
chatpanelt:31014475
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pkg_only:31057982
nativerepl2:31071685
refactort:31084545
pythonrstrctxt:31089940
0c838689:31088353
1iic9185:31091668

```

</details>

**Comment by pwang347** [comment]
Hi @running-machin, thanks for reporting this issue!

Could you please share a few more details to help us investigate?
1) Does this happen with all datasets? E.g. does the following code also run into the same issue?
```python
import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
```
2) If not, could you please share a small sample of data that reproduces the problem?
3) Can you share any errors in the console tab (if any)?
<img width="372" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/8560030/2ff13d6b-bc63-4bf7-a111-284ff42e5a1c">
<img width="377" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/8560030/99bd739f-4550-4acc-bfe6-dfb4eb0aab88">

4) I noticed that you are using WSL, have you also tried to see if the issue reproduces without WSL?

Thank you!

**Comment by running-machin** [comment]
Before I post more info, I need to ask a few questions. Does Data Wrangler only work with pandas' data frames? 

Context:  I have used the extension with Dataframes, and it worked fine. I am having issues when loading with dictionaries. Before I used to use the Jupyter extension that came with the IDE(I think) to check them. Recently I have changed to VS code insider from VS code. and have been using the Jupyter tab near the terminal to look at the variables, in my case the dictionaries(large ones). But I got the notification that it's deprecating soon and suggested to use data wrangler. Now after installing the Data wrangler, When I try to take a look at variables it loads forever.  I have tried to inspect few dictionaries with it and had same conclusion.

**Comment by pwang347** [comment]
Hi @running-machin, thanks for providing the context! Data Wrangler does support viewing dictionary data (not just Pandas DataFrames), so it would be great if you could provide more information such as small sample code on how to reproduce the issue.

**Comment by running-machin** [comment]
There may have been an update where the loading seems quick and doesn't take forever. If there issue appears or persists I will reproduce it this time. But for now, you can close this issue.

**Comment by pwang347** [comment]
@running-machin Sounds good, do feel free to reopen if you see it again. Thanks!
