### ISSUE TITLE
Adding support for compatible data types

### ISSUE THREAD

**Issue by juanfcocontreras** [microsoft/vscode-data-wrangler#226]
When the data type is not natively supported, the "View in data viewer" option does not appear. 

However, before discarding this option, a casting to a `pd.DataFrame(variable)` could be tried internally, and if it does not produce an exception, the "View in data viewer" option could be given. For example, GeoDataFrames from GeoPandas among many other data types could be displayed.

**Comment by pwang347** [comment]
Hi @juanfcocontreras, thank you for making the request! Note that the "View in data viewer" option is currently coming from the Jupyter extension. I would recommend [opening an issue in their repository](https://github.com/microsoft/vscode-jupyter/issues) to support this.

**Comment by juanfcocontreras** [comment]
Done! Thank you so much!

https://github.com/microsoft/vscode-jupyter/issues/15853
