### ISSUE TITLE
Feature Request: search data content

### ISSUE THREAD

**Issue by zhizhongpu** [microsoft/vscode-data-wrangler#235]
In RStudio and the legacy built-in data viewer, like in Excel, one could search the data content using a typed string. i find that function useful.

**Comment by pwang347** [comment]
Hi @zhizhongpu, thank you for opening this feature request! Just wanted to share that we've implemented a text-based search (accessed from same filter menu) that should address this. Please feel free to try it out and let us know if you have any additional feedback. Thanks!
