### ISSUE TITLE
errot loadin csv data into data wrangler

### ISSUE THREAD

**Issue by VamsiReddy17** [microsoft/vscode-data-wrangler#237]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.6.0
-   Python extension version: 2024.10.0
-   .NET Install Tool for Extension Authors extension version: 2.1.1
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "1.5.3",
    "pyspark": "13.3.2",
    "pyarrow": "13.0.0"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.4.2
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (6.05GB free)|
|Process Argv|C:\\Users\\satis\\Downloads\\New folder\\eci_data_2024.csv --crash-reporter-id 0cce76cc-1b06-4bbc-82da-9ea66aecb41d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
legacy_priority:31094926
wkspc-onlycs-c:31100201

```

</details>

**Comment by vamsireddy99** [comment]
check the issue

**Comment by pwang347** [comment]
Hi @VamsiReddy17, thanks for opening this issue! Could you please share more about the error that you received, and if possible to provide a small sample file that can reproduce it?

**Comment by VamsiReddy17** [comment]
i have fixed those issues , thank you
