### ISSUE TITLE
Numpy is not available

### ISSUE THREAD

**Issue by GuangyuanF** [microsoft/vscode-data-wrangler#242]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.6.2024072201
-   Python extension version: 2024.10.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2"
  },
  "required": {
    "pandas": "0.25.2"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.4.2
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.71GB free)|
|Process Argv|--crash-reporter-id 21872e65-ce86-4093-910c-97b31e9d40dd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactorc:31101458
ccplt:31103426
pythonrstrctxt:31103193
wkspc-onlycs-t:31102394

```

</details>

**Comment by pwang347** [comment]
Hi @GuangyuanF, thanks for opening this issue! Could you please share some more information about your setup?
Are you trying to load a torch tensor, and if so what is the package version of torch and numpy?

**Comment by yangtian6781** [comment]
> Hi @GuangyuanF, thanks for opening this issue! Could you please share some more information about your setup? Are you trying to load a torch tensor, and if so what is the package version of torch and numpy?

my torch version is 2.4 and numpy version is 1.26.4, when do you plan to support torch tensor and numpy array?Please

**Comment by GuangyuanF** [comment]
> Hi @GuangyuanF, thanks for opening this issue! Could you please share some more information about your setup? Are you trying to load a torch tensor, and if so what is the package version of torch and numpy?
I've loaded torch. I tried torch2.4 with numpy1.23 and torch2.4 with numpy2.0. But all visions are not available.

**Comment by pwang347** [comment]
Hi @GuangyuanF! Thanks for the reply. I tried with those versions (`torch==2.4.0` + `numpy==1.26.4`, `1.23.0` and `2.0.0`) and they are all working for me.

Do the following code snippets run fine for you?
1. 
```python
import numpy as np
a = np.arange(10).reshape(2, 5)
a
```

2.
```python
import torch
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.numpy()
```

Seems like you could also potentially try downgrading torch (and maybe trying latest numpy 1.26.4 and restarting your Jupyter kernel):
https://github.com/pytorch/pytorch/issues/78341

Thanks!

**Comment by pwang347** [comment]
@yangtian6781 let's discuss more in https://github.com/microsoft/vscode-data-wrangler/issues/249 - thanks!

**Comment by GuangyuanF** [comment]
@pwang347 OK, thank you, I will have a try!

**Comment by pwang347** [comment]
Hi @GuangyuanF, will close this issue as inactive for now. Please feel free to reopen if there's anything I can help with!
