### ISSUE TITLE
Data Wrangler crashes while opening a big dataframe

### ISSUE THREAD

**Issue by Anonymous-Y** [microsoft/vscode-data-wrangler#248]
## Environment data

-   VS Code version: 1.91.1
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.6.0
-   Jupyter Extension version (available under the Extensions sidebar): 2024.6.0
-   Python Extension version (available under the Extensions sidebar): 2024.12.1
-   OS (Windows | Mac | Linux distro) and version: Mac Sonoma 14.6
-   Pandas version: 2.2.1
-   Python and/or Anaconda version: 3.12.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

show dataframe snapshot in data view

## Actual behaviour

Data Wrangler crashes and the kernel is forced to restart. The dataframe that caused the crash contains English texts and symbols like '\n',  '\r,  '\t'. The size of the dataframe is around 10 Mb when it is saved as the .ftr file.

**Comment by pwang347** [comment]
Hi @Anonymous-Y, thanks for reporting! Could you please share some more information below to help with the investigation:
1. Do you have code (or redacted dataset file) that you can share to reproduce this issue?
2. What is the data type of the variable you are trying to view? Do you only run into this issue when launching Data Wrangler and not in the notebook?

Thanks!

**Comment by Anonymous-Y** [comment]
Hi, @pwang347, the crash only happens when I try to open the dataset in Data Wrangler. I can use the notebook default data view to open the dataset. The dataset can also be opened in Excel.

I am sorry that I cannot share the dataset with you, but the dataset contains long text from different documents. It contains 500k rows, and 0.5k-2k English words in each cell. So I suspect that there are some special characters inside the text that caused the crash? Or maybe the dataset is just too large for Data Wrangler?

Thank you!

**Comment by pwang347** [comment]
Hi @Anonymous-Y, thank you very much for your patience and for sharing the sample data! We've identified the issue and have released a fix for the pre-release version 1.7.2. Please give it a try and let us know if the issue is still persisting for you!
