### ISSUE TITLE
Do not automatically open the explorer sidebar window

### ISSUE THREAD

**Issue by yanyu2015** [microsoft/vscode-data-wrangler#256]
Type: <b>Feature Request</b>

When I click on a variable, the Data Wrangler window opens, but I do not want it to automatically open the explorer sidebar. Please do not automatically open the explorer sidebar window!

Extension version: 1.6.0
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by pwang347** [comment]
Hi @yanyu2015, thanks for opening this feature request! This ask is in our backlog and we are currently tracking it here: https://github.com/microsoft/vscode-data-wrangler/issues/96

Please follow the above thread for any updates. Hope this helps!
