### ISSUE TITLE
When debugging in vscode, the tensor data type cannot be viewed and it is always loading data frame.

### ISSUE THREAD

**Issue by coder678** [microsoft/vscode-data-wrangler#259]

**Comment by pwang347** [comment]
Hi @coder678, thanks for opening this issue! Could you please share some more info on how to reproduce the problem:
- What version of torch, numpy and pandas are you using?
- Does the following torch tensor load for you?
```python
import torch
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x
```

If it is working, could you please share a small code snippet that reproduces the failure for you?
Thanks!

**Comment by pwang347** [comment]
Closing this issue as inactive, please feel free to reopen if the issue is persisting for you!

**Comment by TuRan-sino** [comment]
@pwang347 The data wrangler works well with 2-dimensional tensors, but when dealing with tensors of more than 3 dimensions, the dsiplay will be unclear.

```python
import torch


x = torch.randn([1, 2, 3, 4])

print(x)
```
![image](https://github.com/user-attachments/assets/e979496a-ad6e-47b3-bfdb-5cf32da05903)

we need the feature like slice.
