### ISSUE TITLE
Default mode when entering from Explorer

### ISSUE THREAD

**Issue by DavidP2Z** [microsoft/vscode-data-wrangler#261]
Type: <b>Feature Request</b>

# Behaviour

## Expected vs. Actual

There is a setting for the Viewing/Editing behaviour when entering the Data Wrangler from a notebook( dataWrangler.startInEditModeForNotebookEntrypoints).

It would be great to have the same choice when entering the Data Wrangler from a file in the Explorer view. Currently we go straight into editing mode. Perhaps an additional setting called dataWrangler.startEditMoreForExplorerEntrypoints?

## Steps to reproduce:

1. Locate file in the Explorer view, right click and chose Open in Data Wrangler

2. Data Wrangler opens in Editing mode

# Diagnostic data

-   Jupyter extension version: 2024.7.0
-   Python extension version: 2024.12.3
-   .NET Install Tool for Extension Authors extension version: 2.1.1
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2",
    "pyarrow": "17.0.0"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.6.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin x64 23.6.0
Modes:

**Comment by pwang347** [comment]
Hi @DavidP2Z, thank you for opening this request! This issue seems like it is related https://github.com/microsoft/vscode-data-wrangler/issues/192 so I will close it as a duplicate. Please feel free to follow the other thread for any updates!
