### ISSUE TITLE
Feature Request: Default Viewing/Edit Mode, incorrect extension description

### ISSUE THREAD

**Issue by kschutter** [microsoft/vscode-data-wrangler#268]
The description of the extension states that "By default, Data Wrangler opens in the Viewing mode. You can change this behavior in the Settings editor". 
All of my files open in Editing mode, and I'd like the default to actually be viewing instead. 
Requesting that either the default be made to match the extension description, and/or a setting to choose which mode to default to.

**Comment by pwang347** [comment]
Hi @kschutter, thanks for opening this issue! I've merged a README update [here](https://github.com/microsoft/vscode-data-wrangler/pull/272) based on your recommendation to be more clear on what is currently supported. There is also already an issue here for the ask of supporting a setting for changing the view mode:
https://github.com/microsoft/vscode-data-wrangler/issues/192

Please feel free to upvote the issue and/or leave any additional feedback comments there. Thanks!
