### ISSUE TITLE
Pandas doesn't install, wranger doesn't show data

### ISSUE THREAD

**Issue by herrmartins** [microsoft/vscode-data-wrangler#278]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.8.0
-   Python extension version: 2024.14.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {},
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": [
    "pandas"
  ]
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.8.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|19.88GB (7.84GB free)|
|Process Argv|--crash-reporter-id 26203368-4c2b-4479-a2ab-24d9ed076c15|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by pwang347** [comment]
Hi @herrmartins, thank you for opening this issue. Could you please share a screenshot of the issue you are seeing? Do you see any error messages from Data Wrangler, or is it stuck loading forever?

**Comment by herrmartins** [comment]
Hi @pwang347 , thank you for the fast answer.
I can't, because it in the end started working properly.
I've installed data wrangler and, when I first launched it, it complainted that I didn't have pandas. There was a button "install", and it just didn't do nothing..
Then, I tried a few times and nothing... Then I tried some stuff.. I don't know if its required or makes any sense at all, but I've installed pandas and numpy in my virtual environment after that....and I don't remember, what else I did... BUt it finally begun to work..

Thank you for your answer..

**Comment by pwang347** [comment]
No problem, glad you were able to get it working! Generally you should at least see a progress message like this:
<img width="471" alt="image" src="https://github.com/user-attachments/assets/8b28f144-fd64-4cf4-835f-174671463e6a">

Otherwise, if it fails there should be an error message.
<img width="469" alt="image" src="https://github.com/user-attachments/assets/fb41e6a3-afd7-4eed-ad6f-ddff662ae0fa">

Will close the issue for now, but if you can ever get it to appear again please feel free to reopen this. Thanks!
