### ISSUE TITLE
The titantic dataset is incomplete.  Missing columns necessary for the walkthrough analysis

### ISSUE THREAD

**Issue by dokutoshi** [microsoft/vscode-data-wrangler#28]
Type: <b>Bug</b>

# Behaviour
The titantic walthrough video walks through a survivor scenario based on sex (M,F) classes.  However, the sample titanic set included is missing this and other columns.  I eventually found the correct dataset but it was extra effort.  See the attached dataset including the missing columns.
Note: 

- 'parents/children' column is 'Parch'
- 'siblings/spouse' column is 'Sibsp'

## Expected vs. Actual

Expected: Launching the datset for Insiders should load the appropriate dataset.  I am on Mac Ventura

Actual: Dataset is incomplete

## Steps to reproduce:

1. Launch titantic datset in walkthrough

# Diagnostic data

-   Jupyter extension version: 2023.4.1000961023
-   Python extension version: 2023.7.10961009
-   .NET Install Tool for Extension Authors extension version: 1.6.0
- Mac Ventutra 13.3
<details>

<p>

```
XXX
```

</p>
</details>

Extension version: 0.4.0
VS Code version: Code - Insiders 1.78.0-insider (Universal) (3e0b354932b8ddeb099c68ed3b7dfac25350dde2, 2023-04-06T05:23:05.475Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: ena/Users/leonardpimentel/developer/ML/datasets/titanic.csvbled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|13, 14, 11|
|Memory (System)|16.00GB (4.10GB free)|
|Process Argv|--crash-reporter-id e016c85b-9a68-4860-9d1f-f603a9ff439d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192:30661256
azdwalk:30687957
pythonms35:30671666
f08j5886:30680471
57b77579:30687741
pythonclientmv:30700173

```

</details>

**Comment by danv-msft** [comment]
Thank you, @dokutoshi, for using Data Wrangler and for bringing this document discrepancy to our attention. We will take the necessary steps to address it.

**Comment by pwang347** [comment]
Hi @dokutoshi! We've updated the walkthrough dataset to include the missing column, but will keep the column names for 'Parch' and 'Sibsp' as is for now. This should help unblock the walkthrough scenario.

This change will be available in the next release. Thanks for reporting this issue!
