### ISSUE TITLE
Uncaught Error When Trying to Open

### ISSUE THREAD

**Issue by DaniellePashayan** [microsoft/vscode-data-wrangler#282]
## Environment data

-   VS Code version: 1.87.0 (user setup)
-   Data Wrangler Extension version (available under the Extensions sidebar): v1.8.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.2.0
-   Python Extension version (available under the Extensions sidebar): v2024.4.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Pandas version: 2.2.2
-   Python and/or Anaconda version: Python version 3.12.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

To be able to open a dataframe in data wrangler.

## Actual behaviour

Pop up saying "Launching Data Wrangler" and nothing happens or loads. In the extensions window, there's a message that says "This extension has reported 1 uncaught error". Upon clicking, it shows "Je.lm?.onDidChangeChatModels is not a function"

## Steps to reproduce:
1. df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]}). 
2. Button for "Open in Data Wrangler" doesn't appear
3. In Jupyter variable window, click the "Show variable snapshot in data viewer" button

## Logs

<details>
<p>
No outputs get generated and nothing actually loads
![image](https://github.com/user-attachments/assets/3dc01f27-08eb-4c76-9656-02a60d3d5f18)

![image](https://github.com/user-attachments/assets/9973ec60-968f-4d83-8009-3e58f5f00b48)

</p>
</details>

**Comment by pwang347** [comment]
Hi @DaniellePashayan, thank you for reporting this issue! This bug is affecting specific older versions of VS Code, including 1.87. We've released a hotfix in Data Wrangler extension version 1.8.1, please give it a try and let me know if it's fixed for you.

Thanks!

**Comment by DaniellePashayan** [comment]
The hot fix is working, thank you!
