### ISSUE TITLE
Data Wrangler Error

### ISSUE THREAD

**Issue by Noemi135** [microsoft/vscode-data-wrangler#284]
<img width="438" alt="Screenshot 2024-09-14 alle 10 00 41" src="https://github.com/user-attachments/assets/16da7723-6dfa-477e-b0ac-b5a31ba5d17a">

## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @Noemi135, thanks for reporting the issue!

Could you please share what version you are using for the following extensions?
- [Data Wrangler](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.datawrangler)
- [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
- [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)

You can check by viewing from the extensions pane on the left:
![image](https://github.com/user-attachments/assets/419697bb-bd6d-4821-82c0-3bd104e6f527)

Please try enabling this setting to see if it helps resolve the issue for you. Thanks!
<img width="872" alt="image" src="https://github.com/user-attachments/assets/ddcca466-cde5-42d1-a450-7cde2c786df4">
