### ISSUE TITLE
FireDucks Support

### ISSUE THREAD

**Issue by hkrhd** [microsoft/vscode-data-wrangler#286]
## Feature request: FireDucks Support
Can you please add support for the FireDucks.
I often replace 'import pandas' with 'import fireducks.pandas as pd' when pandas is too slow.

Finally, I'm always greatly helped by this extension. Thank you so much

**Comment by pwang347** [comment]
Hi @hkrhd, thanks for opening this feature request! We added it to our backlog and will keep you posted for updates to this.

**Comment by pwang347** [comment]
Hi @hkrhd! We've released a change in pre-release 1.13.2 that should allow viewing DataFrame-derivative types. Could you please try it out and let us know if you have any feedback?
