### ISSUE TITLE
Missing "Export code back to Notebook and exit feature" button

### ISSUE THREAD

**Issue by dokutoshi** [microsoft/vscode-data-wrangler#29]
Type: <b>Bug</b>

# Behaviour
Missing "Export code back to Notebook and exit feature" button

## Expected vs. Actual

Expected: Button should be avaialble on Mac.

Actual: Button is not visible.  There is an option to copy code.

## Steps to reproduce:

1. Launch titantic datset and use walkthrough

# Diagnostic data

-   Jupyter extension version: 2023.4.1000961023
-   Python extension version: 2023.7.10961009
-   .NET Install Tool for Extension Authors extension version: 1.6.0
- Mac Ventutra 13.3
<details>

<p>

```
XXX
```

</p>
</details>

Extension version: 0.4.0
VS Code version: Code - Insiders 1.78.0-insider (Universal) (3e0b354932b8ddeb099c68ed3b7dfac25350dde2, 2023-04-06T05:23:05.475Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|13, 14, 11|
|Memory (System)|16.00GB (4.10GB free)|
|Process Argv|--crash-reporter-id e016c85b-9a68-4860-9d1f-f603a9ff439d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
6233i204:30659907
pythonb192:30661256
azdwalk:30687957
pythonms35:30671666
f08j5886:30680471
57b77579:30687741
pythonclientmv:30700173

```

</details>

**Comment by pwang347** [comment]
@dokutoshi were you perhaps looking for the `Export to Notebook` button here?
![image](https://user-images.githubusercontent.com/8560030/230487892-865c8fab-e32d-4060-a984-91fb99e366af.png)

I am also running the above on Mac. 
If this is not the issue, would you please be able to provide a screenshot of the issue?

Thanks!

**Comment by dokutoshi** [comment]
The walkthrough depicts the available buttons.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/10182821/230497608-c66fb3fb-c095-40d4-b891-381db4cdfcb4.png">

Mac version contains the available buttons.  Are these buttons a 1:! mapping despite descriptions?  
![image](https://user-images.githubusercontent.com/10182821/230497851-e0aca31b-8d25-45de-8520-b9c8c5a85165.png)

**Comment by pwang347** [comment]
@dokutoshi Great catch - yes, we actually show different buttons depending on how the launch occurred.

If starting from a notebook file, it should be the one shown in the walkthrough (note also that the string has been updated and should now look like this - `Back to notebook`)
![image](https://user-images.githubusercontent.com/8560030/230499249-5035c53c-231f-4ba1-90b4-22c668793806.png)

When launching from a different file (e.g. CSV) you will see the latter button, and it essentially does the same thing except that it will create a new notebook instead of exporting to an existing one.

**Comment by pwang347** [comment]
Closing the issue as designed, thanks!
