### ISSUE TITLE
Cannot load out

### ISSUE THREAD

**Issue by JianxiangL** [microsoft/vscode-data-wrangler#290]
## Environment data

-   VS Code version: 1.93.1
-   Data Wrangler Extension version (available under the Extensions sidebar): 1.9.4
-   Jupyter Extension version (available under the Extensions sidebar): 2024.8.1
-   Python Extension version (available under the Extensions sidebar): 2024.10.1
-   OS (Windows | Mac | Linux distro) and version: win11
-   Pandas version: 2.0.3
-   Python and/or Anaconda version: 3.8.19
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Expected behaviour

display the value of the array

## Actual behaviour

loading data frame......  i have wait for a long long long long time
![image](https://github.com/user-attachments/assets/b7c71496-093a-48b8-beb0-1887da211f7a)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

![image](https://github.com/user-attachments/assets/d20cd77d-d921-4ce2-b008-f8f758c5d36b)

## Logs

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

```
Visual Studio Code (1.93.1, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: win32 (x64).
Temp Storage folder ~\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\version-2024.8.1
Workspace folder e:\Study\E2NeRF, Home = c:\Users\ljx
19:29:17.882 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"event_data","type":"Tensor","count":4,"shape":"(4, 640000)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":17,"fullType":"torch.Tensor"}
19:29:56.796 [info] Ending debug session d0872720-086c-4bea-83e6-19e9b3ca8d9e
19:29:56.796 [info] Ending debug session d0872720-086c-4bea-83e6-19e9b3ca8d9e
19:33:46.411 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"event_data","type":"Tensor","count":4,"shape":"(4, 640000)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":18,"fullType":"torch.Tensor"}
19:36:52.018 [info] Ending debug session fdeb68c3-07ec-4439-b137-438fb15fa1e8
19:36:52.018 [info] Ending debug session fdeb68c3-07ec-4439-b137-438fb15fa1e8
19:38:34.409 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"event_data","type":"Tensor","count":4,"shape":"(4, 640000)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":17,"fullType":"torch.Tensor"}
19:49:39.735 [info] Ending debug session 961add08-d4f2-4484-bfa7-6a560621951b
19:49:39.735 [info] Ending debug session 961add08-d4f2-4484-bfa7-6a560621951b
19:51:04.182 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"event_data","type":"Tensor","count":4,"shape":"(4, 640000)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":17,"fullType":"torch.Tensor"}
```

lanch.json:
```
{"version": "0.2.0",
    "configurations": [
        {
            "name": "Python 调试程序: 当前文件",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {"PYDEVD_WARN_EVALUATION_TIMEOUT": "500"},
        }
    ]
}
```

**Comment by pwang347** [comment]
Hi @JianxiangL, thank you for reporting the issue! Could you please check if there are any logs related to Data Wrangler in the console window?

You can open it like this from command palette (ctrl+shift+P):
<img width="612" alt="image" src="https://github.com/user-attachments/assets/3d105a6e-4ceb-492e-ad4e-ce0f5b50e62b">

Then check for errors here:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/9e208440-f49e-443d-8350-e4c197fcd620">

Do you still see the issue if you manually convert the variable to another type, e.g., Pandas or NumPy?

Thanks!

**Comment by JianxiangL** [comment]
> 您好，感谢您报告此问题！您能否检查控制台窗口中是否有任何与 Data Wrangler 相关的日志？
> 
> 您可以从命令面板 （ctrl+shift+P） 中按如下方式打开它： <img alt="图像" width="612" src="https://private-user-images.githubusercontent.com/8560030/370082565-3d105a6e-4ceb-492e-ad4e-ce0f5b50e62b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjI5ODUsIm5iZiI6MTcyNzE2MjY4NSwicGF0aCI6Ii84NTYwMDMwLzM3MDA4MjU2NS0zZDEwNWE2ZS00Y2ViLTQ5MmUtYWQ0ZS1jZTBmNWI1MGU2MmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDcyNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYxMmI3N2VjYzViNzZlMjQ0Yzg3ZWRlM2MwN2FkNWI3MGM0YTNmMDZlNTczM2RiMTQ4MTgyNWZkMGFlZmU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AZF90UHphEYKi0zjXAfkye_EC5SKzc1is-8KeepqfPk">
> 
> 然后在此处检查错误： <img alt="图像" width="520" src="https://private-user-images.githubusercontent.com/8560030/370082659-9e208440-f49e-443d-8350-e4c197fcd620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjI5ODUsIm5iZiI6MTcyNzE2MjY4NSwicGF0aCI6Ii84NTYwMDMwLzM3MDA4MjY1OS05ZTIwODQ0MC1mNDllLTQ0M2QtODM1MC1lNGMxOTdmY2Q2MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDcyNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJkNTZiNTQ2YjQ2MTVlOTEzOTE2ZDg5OGFmMjcxYzJkZGNlYTlhM2I2NTI2NjUxYmQ1NzQwZmRmYTkxNjQxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.90OuneSSFBqpP-BBuzjNaNbnYVLLusjlIal8CTXpUQg">
> 
> 如果您手动将变量转换为其他类型（例如 Pandas 或 NumPy），是否仍然会看到问题？
> 
> 谢谢！
我查看size小一点的tensor可以瞬间加载出来size(200,4,4)，但是加载大的还是不行。
我把event_data这个tensor转换成了numpy，也是加载不出来。控制窗口有这些内容：（看不懂......）
![image](https://github.com/user-attachments/assets/420ce14d-eace-4685-9690-3059a68c1fc5)
![image](https://github.com/user-attachments/assets/1e1adf6e-96dd-4be2-a193-d02b0e6bf8f0)
![image](https://github.com/user-attachments/assets/455cdb70-7631-410e-a137-24a75e026db1)
![image](https://github.com/user-attachments/assets/095d875d-e106-4c36-af43-3072190f8b37)
![image](https://github.com/user-attachments/assets/aeb20628-cad1-41aa-a374-b772e1b7a303)
![image](https://github.com/user-attachments/assets/3f4a3526-1a11-42d9-8663-21fe545f255a)

**Comment by pwang347** [comment]
Hi @JianxiangL, thanks for the response! It looks like you might have a large number of columns actually (640000?), which is why it can be very slow. Currently column loading is not fully virtualized due to technical reasons, but if this is something you would be interested in it would be great if you could open a feature request!

As a temporary workaround, does taking the transpose of the dataset help mitigate the problem for you?

**Comment by JianxiangL** [comment]
> Hi @JianxiangL, thanks for the response! It looks like you might have a large number of columns actually (640000?), which is why it can be very slow. Currently column loading is not fully virtualized due to technical reasons, but if this is something you would be interested in it would be great if you could open a feature request!
> 
> As a temporary workaround, does taking the transpose of the dataset help mitigate the problem for you?

work!!!! thanks

**Comment by pwang347** [comment]
Thank you for confirming! Will close this issue now since it is resolved, but we've added an item to our backlog to investigate improving column loading performance. Hope this helps!
