### ISSUE TITLE
Feature Request: Clicking the Filters condition should expand the dropdown.

### ISSUE THREAD

**Issue by kschutter** [microsoft/vscode-data-wrangler#296]
Currently, in order to expand the dropdown for filters, you need to click the small dropdown arrow on the right side of the dialog. If you click the text "Select a condition", it just becomes a text field that you can search conditions which. It would be more intuitive if, at the same time it becomes an enterable text field, the dropdown populated as well.

**Comment by pwang347** [comment]
Hi @kschutter, thanks for making this feature request! We've merged a change enabling this and also supporting a mode for quicker filters in pre-release version 1.15.1. Please feel free to try it out and let us know if you have any additional feedback. Thanks!
