### ISSUE TITLE
Issue: Message - "A Data Viewer Extension is required to view data frames." 

### ISSUE THREAD

**Issue by brentonmcs** [microsoft/vscode-data-wrangler#307]
## Environment data

-   VS Code version: 1.94.0 
-   Data Wrangler Extension version (available under the Extensions sidebar): 
v1.10.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.9.1
-   Python Extension version (available under the Extensions sidebar): v2024.16.0
-   OS (Windows | Mac | Linux distro) and version: Mac OS 15.0
-   Pandas version: 2.2.3
-   Python and/or Anaconda version: 3.11.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

To open up the Data Viewer

## Actual behaviour

A pop up to install the extension. "A Data Viewer Extension is required to view data frames. "

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Start Debugging
2. Right click a data frame and "View value in Data Viewer"
3. Pop up to install comes up.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.94.0, undefined, desktop)
Jupyter Extension Version: 2024.9.1.
Python Extension Version: 2024.16.0.
Pylance Extension Version: 2024.9.2.
Platform: darwin (arm64).
Temp Storage folder ~/Library/Application Support/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.9.1
Workspace folder ~/repos/dat-XXXX, Home = /Users/brenton

```

</p>
</details>

**Comment by pwang347** [comment]
Hi @brentonmcs, thanks for opening this issue!

Could you please share some more details:
* What type of variable are you trying to load? E.g., can you view a simple variable like `l = [1,2,3]`?
* Do you have the setting mentioned in this comment? https://github.com/microsoft/vscode-data-wrangler/issues/129#issuecomment-1922177014 if so, could you please follow the steps to address it?

It would also be helpful if you could enable debug level logs for the Jupyter output as I don't see the logs associated with Jupyter variable viewing there. You can do this with the following setting:
<img width="733" alt="image" src="https://github.com/user-attachments/assets/60e8cd42-2349-4f4d-831b-5114e79e2990">

Thank you!

**Comment by brentonmcs** [comment]
Looks like adding in "ms-toolsai.datawrangler": 1 to my settings fixes the issue.

**Comment by yinrong** [comment]
> Looks like adding in "ms-toolsai.datawrangler": 1 to my settings fixes the issue.

not working now.

**Comment by BoltCitizen** [comment]
I have this issue as well. Cant inspect the content of a DataFrame. Same error message: "A Data Viewer Extension is required to view data frames."

Can we re-open please?
