### ISSUE TITLE
Viewing a dictionary is cluttered and difficult to read.

### ISSUE THREAD

**Issue by weavermech** [microsoft/vscode-data-wrangler#308]
Hiya,

 If I'm opening a dictionary I'd like to be able to quickly and easily get a feel for the data. 

At the moment (I couldn't see any way to change this) the layout is not easy to read. The keys and values get lost amongst other text (Missing, Disticnt, big blue bars, Min, Max), and on initial opening I can only see 6 entries. 
Scrolling does nothing, as it's presented as one long row.

Similar to a list I think it'd be good to see a column view of keys and values, as many as possible. It should be set out in an easily readible format, any meta data could be off to the side. Scrolling would scroll through the data.

Current view:
![space](https://github.com/user-attachments/assets/4c0bd15e-94a9-4023-8eef-733cbe3bab0f)

**Comment by pwang347** [comment]
Hi @weavermech, we've released a fix in pre-release 1.13.2 that should address this issue. Please feel free to give it a try and let us know what you think. Thanks again for the feedback!

**Comment by weavermech** [comment]
I just had a quick look and it's great, much more readable and navigateable! Thanks, and good work 👍🏼
