### ISSUE TITLE
“Support for DataFrame type in Data Wrangler

### ISSUE THREAD

**Issue by ReemAbdelazim-md** [microsoft/vscode-data-wrangler#309]
I am currently trying view some tables that were changed in the local variables in the debugger. 
A very simple example is when this Part of the code runs " combined_df.join", and I try to right click and view value in data viewer, I get the following error:
![image](https://github.com/user-attachments/assets/3f8bb514-a865-46e1-848d-b4be845a8b0b)
Can I get some guidance on what my next steps should be cause most issues I read show that you can view your tables from the debugger, but for some reason it is not working on my end. 
Note: I have both the python and Jupyter extensions downloaded.

**Comment by pwang347** [comment]
Hi @ReemAbdelazim-md, thank you for reporting this!

Could you please help provide some more information:
* Are you able to load a simple variable like this while debugging? `l = [1,2,3]`
* What is the DataFrame type you are loading? Is it Pandas?
* Do you have any libraries that modify the behaviour of your DataFrame type? We currently do not support wrapper libraries such as Modin, FireDucks.

**Comment by ReemAbdelazim-md** [comment]
I am trying to pull data using data connect, manipulate it and then view it using pyspark. The Dataframe type that I am using is pyspark.sql

**Comment by pwang347** [comment]
Hi @ReemAbdelazim-md, thanks for the response! PySpark currently requires enabling this setting (we plan to remove this soon):
![image](https://github.com/user-attachments/assets/291cfc78-c2b2-4e29-901c-d4fc44229c35)

Could you please try enabling this and try it again?

**Comment by ReemAbdelazim-md** [comment]
I had it enabled, and still the same problem.

**Comment by pwang347** [comment]
Hmm, that's strange that the setting has no effect for you. Have you tried reloading VS Code in case it's in a weird state?

Also just to be sure, is this what you are trying?
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/ce00afc1-ddd1-4a27-a54d-8b018bac3db4">

The above loads correctly for me when I have the setting enabled, but disabled I get the same error message as you:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/47e6ba42-c29c-4659-9933-33a85a02e212">

Here is the code below, does it also work for you?
```python
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
from datetime import datetime, date
import pandas as pd
from pyspark.sql import Row

df = spark.createDataFrame([
    Row(a=1, b=2., c='string1', d=date(2000, 1, 1), e=datetime(2000, 1, 1, 12, 0)),
    Row(a=2, b=3., c='string2', d=date(2000, 2, 1), e=datetime(2000, 1, 2, 12, 0)),
    Row(a=4, b=5., c='string3', d=date(2000, 3, 1), e=datetime(2000, 1, 3, 12, 0))
])
df # <- breakpoint here
```

**Comment by pwang347** [comment]
Could you please let me know what is the output of this code?

```python
import pyspark
ver = pyspark.__version__
print(ver)
is_pyspark = isinstance(df, pyspark.sql.dataframe.DataFrame) # replace 'df' with your DataFrame variable
print(is_pyspark)
```

**Comment by ReemAbdelazim-md** [comment]
For the following code:
import pytest
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
from datetime import datetime, date
from pyspark.sql import Row
import pyspark

ver = pyspark.__version__
print(ver)

df = spark.createDataFrame([
    Row(a=1, b=2., c='string1', d=date(2000, 1, 1), e=datetime(2000, 1, 1, 12, 0)),
    Row(a=2, b=3., c='string2', d=date(2000, 2, 1), e=datetime(2000, 1, 2, 12, 0)),
    Row(a=4, b=5., c='string3', d=date(2000, 3, 1), e=datetime(2000, 1, 3, 12, 0))
])

is_pyspark = isinstance(df, pyspark.sql.dataframe.DataFrame) # replace 'df' with your DataFrame variable
print(is_pyspark)

if __name__ == "__main__":
    pytest.main([__file__])
    
    This the output:|
    
![image](https://github.com/user-attachments/assets/ab05c54c-5710-40ec-8dec-e71fa922091f)


I don't know if this will make sense, but I have  a sparkengine class that is what I import in order to use to start ,y spark sessions as follows:

from databricks.connect import DatabricksSession
from pyspark.sql import SparkSession

def create_spark_engine() -> SparkSession:
    """
    Creates and returns a SparkSession instance using Databricks Connect.

    This function initializes a DatabricksSession, which is required when running 
    Spark applications with Databricks Connect.
    
    :return: A DatabricksSession object to be used for Spark operations.
    :rtype: SparkSession
    """
    return DatabricksSession.builder.getOrCreate()

# Initialize Spark session
spark: SparkSession = create_spark_engine()

**Comment by pwang347** [comment]
Hi @ReemAbdelazim-md, I meant if you could run only this code (and not any of the other code), you will need to replace "df" with the DataFrame you are trying to load:

```python
import pyspark
ver = pyspark.__version__
print(ver)
is_pyspark = isinstance(df, pyspark.sql.dataframe.DataFrame) # replace 'df' with your DataFrame variable
print(is_pyspark)
```

But I see that you are using DataBricks, so I will test to see if this is caused by having a different path there. Will update the thread when I get a chance to try it out. Thanks!

**Comment by pwang347** [comment]
Hi @ReemAbdelazim-md, I was able to try running the code in DataBricks and it seems to be outputting what I expected. However, I wasn't able to try it with DataBricks Connect with my compute settings. Here is my output from running the above:

```
3.5.0
True
```

Could you please confirm the following two things:
1. Can you try loading a regular variable such as `l = [1,2,3]`? If not, then it may be that DataBricks Connect in general is not supported, in which case we may need more investigation.
2. Can you please share the output for running the code I shared in the previous comment? It would be great to know which version of pyspark you are on, and if there are any issues with the type check.

Thanks!

**Comment by ReemAbdelazim-md** [comment]
I was able to run the following code:
import pytest
from datetime import datetime, date
from pyspark.sql import Row
from src.spark_engine import spark

df = spark.createDataFrame([
    Row(a=1, b=2., c='string1', d=date(2000, 1, 1), e=datetime(2000, 1, 1, 12, 0)),
    Row(a=2, b=3., c='string2', d=date(2000, 2, 1), e=datetime(2000, 1, 2, 12, 0)),
    Row(a=4, b=5., c='string3', d=date(2000, 3, 1), e=datetime(2000, 1, 3, 12, 0))
])

if __name__ == "__main__":
    pytest.main([__file__])

I can view the data if I transfer it into pandas, but not when it is a dataframe. Would that be a sparks issue cause I am noticing that most of the highlighted parts in the debug console are the sparks part.

**Comment by pwang347** [comment]
What version of pyspark are you using? We check type using the `isinstance` code above, so if that doesn't pass on your version we might need to update it.

**Comment by ReemAbdelazim-md** [comment]
for some reason  pyspark --version is showing nothing.

**Comment by ReemAbdelazim-md** [comment]
for reference, I was able tot get the databricks extension working so now instead I am using the extension

**Comment by kycutler** [comment]
Hi @ReemAbdelazim-md, thank you for the information and your cooperation.

Will you please run the following code using your dataframe variable and share the exact output:

```python
print(type(df))
```

It should look something like `<class 'pyspark._________________.DataFrame'>`. Looking to confirm that your data is the type we expect, as PySpark actually has multiple classes of DataFrame internally.

**Comment by Rooth123** [comment]
Hi @kycutler I am recieving the same issues. Using Databricks Extension (which I believe uses Databricks Connect v2). Running your code on my dataframe I am trying to view I get this:

3.5.0

False

<class 'pyspark.sql.connect.dataframe.DataFrame'>

It seems the DataFrame is of the "connect" class?

**Comment by ReemAbdelazim-md** [comment]
Mine is: 
<class 'pyspark.sql.connect.dataframe.DataFrame'>

**Comment by pwang347** [comment]
Hi @Rooth123, @ReemAbdelazim-md  - we've added support for `pyspark.sql.connect.dataframe.DataFrame` in pre-release 1.13.1. Note that you will still need this setting enabled ![Image](https://github.com/user-attachments/assets/1e6c261d-136c-4bb4-9d4d-696b80728499)

Could you please give this a try and let us know if this helps address your scenario? Thanks!

**Comment by bestekov** [comment]
@ReemAbdelazim-md  (and @pwang347 in case this comes up in another issue), the reason you may be having issues is that if you are using the Databricks connect extension, they replace your local `pyspark` with a facade that supports intellisense but does not actually have any of the Spark code. So, I suspect that when interacting with the wrangler it may be trying to run Spark code locally which doesn't actually exist.

In order to do local unit testing we had to run in an pyenv where we did NOT install the Databricks connect extension and instead just used the public pyspark installation.
