### ISSUE TITLE
Bug: Clicking "Filter" in toolbar does not close the filter popup

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-data-wrangler#316]
![Image](https://github.com/user-attachments/assets/19967990-f972-43ad-bf26-3eedc5f84f63)

Repro steps:
1. Open DW in View mode
2. Add one filter
3. Click "1 Filter" in the top toolbar to open the filter context menu
4. Click the same "1 Filter" button again

Expected: The filter context menu closes

Actual: The filter context menu does not close

**Comment by pwang347** [comment]
This is fixed in pre-release 1.13.1. Thanks!
