### ISSUE TITLE
Show notebook name in tab title when two dataframes from separate notebooks share the same name.

### ISSUE THREAD

**Issue by AWH1122** [microsoft/vscode-data-wrangler#325]
If I have two notebooks with dataframes that share the same name, the second dataframe to be viewed gets numbered {dataframe_name} (2). It would be nice if these datawrangler tabs were distiguished by the notebook that they originated from as I believe this information would be more useful, rather than just numbering oldest to newest.

Just a thought anyway!

**Comment by pwang347** [comment]
Hi @AWH1122, thanks for opening this issue! I believe this should already be supported. In the following example I have two different notebooks with the same variable name (so the notebook name appears as secondary text in the tab):
![Image](https://github.com/user-attachments/assets/c746942a-3cbb-45ad-b55f-0a519e0e7f5b)

Repeated launches of the same variable from the same notebook will open it as `{dataframe_name} (2)`. Is this what you were asking for?

**Comment by AWH1122** [comment]
Hi, I am not sure what happened that caused the behaviour that I described but after checking again, the expected behaviour is demonstrated. Thanks for your help!
