### ISSUE TITLE
numpy.core.multiarray failed to import Numpy installed

### ISSUE THREAD

**Issue by NetZissou** [microsoft/vscode-data-wrangler#329]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.10.0
-   Python extension version: 2024.18.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.3",
    "pyarrow": "15.0.2"
  },
  "required": {
    "pandas": "1.2.0",
    "pyarrow": "0.0.1"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterCellStatusBar
-   Active mode: dataViewer

Extension version: 1.12.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 3.10.0-1160.125.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.46GB (13.55GB free)|
|Process Argv|--crash-reporter-id cb5d1f66-2b03-4a1f-b4a3-e0472a2a9997|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pitzer.osc.edu|
|OS|Linux x64 3.10.0-1160.125.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (40 x 2982)|
|Memory (System)|375.65GB (329.03GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by NetZissou** [comment]
The extension used the system's default Python instead of the one in the virtual environment or the selected kernel interpreter for the notebook. Installing `pandas` `numpy` `pyarrow` on system's default Python solved this issue.

**Comment by pwang347** [comment]
Hi @NetZissou, thank you for opening this issue!
Regarding this:
> The extension used the system's default Python instead of the one in the virtual environment or the selected kernel interpreter for the notebook.

We gain access to the kernel using the Jupyter extension's API, so if the behaviour is unexpected, please feel free to open an issue here and attach the relevant logs following their issue template: https://github.com/microsoft/vscode-jupyter/issues

Thanks!
