### ISSUE TITLE
Data Wrangler fails to display in-memory DataFrame

### ISSUE THREAD

**Issue by danhje** [microsoft/vscode-data-wrangler#330]
## Environment data

-   VS Code version: 1.94.2
-   Data Wrangler Extension version: v1.12.1
-   Jupyter Extension version: v2024.9.1 (update to v2024.10.0 fails, even after reinstalling)
-   Python Extension version: v2024.18.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11 with WSL
-   Pandas version: 2.2.3
-   Python and/or Anaconda version: 3.12.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): uv venv

## Expected behaviour

DW displays in-memory DF

## Actual behaviour

A blank DW-windows appears.

## Steps to reproduce:

Run this with a breakpoint at `pass`:
```python
import pandas as pd
df = pd.DataFrame({"col": [1, 2, 3]})
pass
```

Right click `df` in Variables plane and select "View Value in Data Viewer".

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel</summary>

<p>

```text
Visual Studio Code (1.94.2, wsl, desktop)
Jupyter Extension Version: 2024.9.1.
Python Extension Version: 2024.18.0.
Pylance Extension Version: 2024.11.1.
Platform: linux (x64).
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.9.1
Workspace folder [removed], Home = [removed]
09:11:10.093 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"df","type":"DataFrame","count":3,"shape":"(3, 1)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":8,"fullType":"pandas.core.frame.DataFrame"}
09:13:34.562 [info] Showing data viewer with command dataWrangler.launchDataViewer for variable {"name":"df","type":"DataFrame","count":3,"shape":"(3, 1)","size":0,"supportsDataExplorer":false,"value":"...","truncated":false,"frameId":8,"fullType":"pandas.core.frame.DataFrame"}
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @danhje, thank you for opening this issue and we're sorry that you're running into it!

I've also encountered issues with panels sometimes being empty while VS Code is being updated, and I see that you're on an older VS Code version (latest should now be 1.95.1 at time of writing). I would recommend installing the latest patch and reopening VS Code to see if it helps resolve the issue.

If this doesn't help, could you please share your console logs when the issue occurs? You can access that from the command palette (with ctrl+shift+P) and the following text:
![Image](https://github.com/user-attachments/assets/e0dae06f-c23f-4e50-a740-8fb1a780d2d4)

It would be great if you could share any error messages you see in the console logs. Thanks!
