### ISSUE TITLE
Make it optional whether the datawrangler side panel is opened

### ISSUE THREAD

**Issue by warfl0p** [microsoft/vscode-data-wrangler#331]
I think it would imporve the user experience if it was optional for the extension to open the Data Wrangler sidebar. Often I just use Data Wrangler to open parquet files, and don't need to do anything in the side bar. The bar opening is anoying when:
- I am switching trough files in the Explorer side tab (I always have to go back to the explorer after opening something in Data Wrangler)
- I have the sidebar completely hidden to have more space on my screen. (when opening files with ctrl+tab or ctr+p, always have to collapse the sidebar)

**Comment by pwang347** [comment]
Hi @warfl0p, thanks for opening this issue! We've just released an update in pre-release 1.13.3 that adds a setting to make this optional. For more details, please see https://github.com/microsoft/vscode-data-wrangler/issues/96#issuecomment-2487056292
