### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by samuelwerplotz** [microsoft/vscode-data-wrangler#334]
- Issue Type: `Performance`
- Extension Name: `datawrangler`
- Extension Version: `1.12.0`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.94.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/spw/AppData/Local/Temp/ms-toolsai.datawrangler-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by pwang347** [comment]
Hi @samuelwerplotz, thank you for opening this issue. Could you please attach the file mentioned here so we could investigate? `file:///c%3A/Users/spw/AppData/Local/Temp/ms-toolsai.datawrangler-unresponsive.cpuprofile.txt`

Thanks!

**Comment by samuelwerplotz** [comment]
[ms-toolsai.datawrangler-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/17668413/ms-toolsai.datawrangler-unresponsive.cpuprofile.txt)

**Comment by pwang347** [comment]
Thank you for providing the extra information @samuelwerplotz, based on the call stack I've transferred this issue onto the tas-client repository here: https://github.com/microsoft/tas-client/issues/73
