### ISSUE TITLE
Allow CTRL + C on cells. Right click and copy is a small but very annoying thing.

### ISSUE THREAD

**Issue by DireWolfCoder** [microsoft/vscode-data-wrangler#335]
## Environment data

-   VS Code version: XXX
-   Data Wrangler Extension version (available under the Extensions sidebar): XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Pandas version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by pwang347** [comment]
Hi @DireWolfCoder, thank you for opening this issue! Just wanted to let you know that we've released an update to support this in pre-release version 1.13.3. Please feel free to give it a try and let us know if you have any additional feedback. Cheers!
