### ISSUE TITLE
Could not retrieve variable df_holdings from the Jupyter extension.

### ISSUE THREAD

**Issue by denisgeogeo** [microsoft/vscode-data-wrangler#336]
Could not retrieve variable df_holdings from the Jupyter extension. Please file an issue on the Data Wrangler GitHub repository.

Trying to open a simple dataframe in Data Wrangler. I thought it was due to a faulty installation of the extension from my side, but the issue persisted even after deleting all extensions using the command prompt and installing them again via the default suggestions for python + Data Wrangler. 

Prior to this hard reset of the extensions, I didn't even get the error that the variable can't be retrieved, I only got an endless loading of the Data Wrangler extension.

**Comment by pwang347** [comment]
Hi @denisgeogeo, thanks for opening this issue! Could you please check if this discussion applies to you? https://github.com/microsoft/vscode-data-wrangler/issues/321#issuecomment-2438974657

**Comment by denisgeogeo** [comment]
hey @pwang347 Thanks a lot for the feedback. Yes, this solved the issue.
