### ISSUE TITLE
data summary automatically pops up

### ISSUE THREAD

**Issue by catherinewjr** [microsoft/vscode-data-wrangler#337]
When I use VSCode, the sidebar is set to close by default. However, every time I open Data Wrangler, the Data Summary sidebar automatically pops up. Is there a way to set the sidebar to stay closed?

**Comment by pwang347** [comment]
Hi @catherinewjr, thanks for opening this issue! Just wanted to let you know that there should now be a setting to enable this in pre-release version 1.13.3. For more details, please see https://github.com/microsoft/vscode-data-wrangler/issues/96#issuecomment-2487056292
