### ISSUE TITLE
Feature request: Add support also for .parquet files

### ISSUE THREAD

**Issue by diego-pm** [microsoft/vscode-data-wrangler#34]
It would be awesome that data wrangler was able to open/export to parquet files. This is a widely used format, so it would be great to have support for this.

**Comment by danv-msft** [comment]
Thank you for trying out Data Wrangler, and for reaching out to us, @diego-pm. 

We will address this request in the upcoming releases scheduled for May.

**Comment by jruales** [comment]
Hi @diego-pm, the requested functionality is now available in Data Wrangler pre-release version 0.13.1. This option can be enabled in the settings and requires the `pyarrow` package to be installed:
![image](https://github.com/microsoft/vscode-data-wrangler/assets/1588988/5808980a-492e-463f-9f7b-4f75eb4800df)

After doing that, you'll be able to export Parquet files:
![image](https://github.com/microsoft/vscode-data-wrangler/assets/1588988/3ea338ca-5578-49ac-8d95-6ebf1f30f672)

Please let us know if you run into any issues.
