### ISSUE TITLE
"pyarrow" Module not found

### ISSUE THREAD

**Issue by dvignacioglobal** [microsoft/vscode-data-wrangler#343]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.10.0
-   Python extension version: 2024.20.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.3",
    "pyarrow": "18.0.0"
  },
  "required": {
    "pandas": "1.2.0",
    "pyarrow": "0.0.1"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterNotebookToolbar
-   Active mode: dataViewer

Extension version: 1.12.1
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7735HS with Radeon Graphics         (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.25GB (2.58GB free)|
|Process Argv|--crash-reporter-id 640abfba-8109-4294-ba35-2cde047a6b2c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by pwang347** [comment]
Hi @dvignacioglobal, thanks for opening this issue! Could you please share some more details about the error you are encountering such as a screenshot?

From the error message you shared it seems like you might have a faulty pyarrow installation. Are you able to run the following command in your notebook?
```python
import pyarrow
print(pyarrow.__version__)
```

**Comment by dvignacioglobal** [comment]
Hi, I solved the installation problem by uninstalling and reinstalling pyarrow.  Might be in the way how Datawrangler detects dependencies. Thanks!
