### ISSUE TITLE
Opening editor window, when DataWrangler opens

### ISSUE THREAD

**Issue by Lexislex** [microsoft/vscode-data-wrangler#346]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: 2024.10.0
-   Python extension version: 2024.20.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.2",
    "pyarrow": "16.1.0"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterNotebookToolbar
-   Active mode: dataViewer

Extension version: 1.12.1
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 14fafac9-5949-4c76-8ddb-4d4164dd3620|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by pwang347** [comment]
Hi @Lexislex, could you please check if the steps [here](https://github.com/microsoft/vscode-data-wrangler/issues/96#issuecomment-2487056292) address the issue for you?

**Comment by Lexislex** [comment]
hi @pwang347 , it doesn't work :(
<img width="1130" alt="Image" src="https://github.com/user-attachments/assets/918ba996-b29e-427f-8d5d-66e9c216b9e3" />
<img width="643" alt="Image" src="https://github.com/user-attachments/assets/dffe97ab-a489-4e23-a687-f4b386720b6b" />

**Comment by pwang347** [comment]
Hi @Lexislex, seems like I misunderstood the issue! What you're seeing here is very strange, it can happen if VS Code is not able to find Data Wrangler's editor registration. Could you please try the following:

1. Uninstall Data Wrangler and reinstall it
2. If the above does not help, can you please share if you see anything here? (Under Features > Runtime Status)
![Image](https://github.com/user-attachments/assets/6dbba597-69fe-4637-8927-25be98c0c1e5)

**Comment by Lexislex** [comment]
Hi, @pwang347 
I did as you wrote, but nothing helped.
When you open a tab with DataWrangler, an empty editor with the same name opens. After closing the first tab, this tab with an empty editor remains, and if you try to close it while the DataWrangler is running, it opens again automatically. It cannot be closed until you close the DataWrangler window
This problem repeats on my second windows computer as well
<img width="776" alt="Image" src="https://github.com/user-attachments/assets/b2023560-406a-4cef-87c5-569a336a57c1" />
<img width="751" alt="Image" src="https://github.com/user-attachments/assets/56ac01f2-b864-4cd9-8d5a-2204bfb92079" />
<img width="916" alt="Image" src="https://github.com/user-attachments/assets/e219e4cd-2131-4235-a3ba-9552bd484dd9" />

**Comment by Lexislex** [comment]
when opening a csv, this problem also exists
<img width="1102" alt="Image" src="https://github.com/user-attachments/assets/d05b684c-4120-4f58-a064-ffaa0f663d0e" />
<img width="679" alt="Image" src="https://github.com/user-attachments/assets/2093719e-745f-40cd-9012-2cd3eb6f84e8" />

**Comment by pwang347** [comment]
Hi @Lexislex, if it is happening on both your Mac and Windows machine I am thinking it might be due to some VS Code setting that is being synced. Could you please try disabling all VS Code settings?

For example:
1. Press Ctrl+shift+P or Cmd+shift+P to open command palette
2. Type the following command:
<img width="631" alt="Image" src="https://github.com/user-attachments/assets/8dff5b66-e0e7-4ed8-a8f0-f2bf67213f73" />

3. Select all lines, then run the following command
<img width="615" alt="Image" src="https://github.com/user-attachments/assets/4ee8cf5c-b3e4-470b-926a-65032636310a" />

That could help isolate what the issue is.

--

Separately, do you also see any error or warning messages in the developer console? You can access that with the following command:
<img width="604" alt="Image" src="https://github.com/user-attachments/assets/69cd4fa5-097c-4ce9-9363-806c0f3c16a3" />

Thanks!

**Comment by Lexislex** [comment]
![Image](https://github.com/user-attachments/assets/1d54a63d-d095-426e-a083-6ccc09ab9d98)

**Comment by Lexislex** [comment]
Thanks Paul!
I seem to have found the problem. 
I saw an error in the console related to GigaCode, disabled it and now the DataWrangler opens correctly.
Thanks!
