### ISSUE TITLE
ctrl+tab does nothing instead of switching tabs

### ISSUE THREAD

**Issue by Ar-Kareem** [microsoft/vscode-data-wrangler#347]
Type: <b>Bug</b>

# Behaviour

ctrl+tab shortcut not working

## Expected vs. Actual

Expected: ctrl+tab goes to the next tab

Actual: ctrl+tab does nothing no matter how many times it's pressed

## Steps to reproduce:

1. open any .csv file in data wrangler (or any other file I think) + open any other tab next to data wrangler (.py file for example)

2. click on one of the cells inside the data wrangler tab (you must do this otherwise the bug doesn't happen)

3. use the universal keyboard shortcut "ctrl+tab" to go to the next tab in the vscode editor (e.g. go from the data wrangler tab to the .py tab)

# Diagnostic data

-   Jupyter extension version: 2024.10.0
-   Python extension version: 2024.20.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.2.3",
    "pyarrow": "18.0.0"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.12.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'SSH: somerset.csail.mit.edu' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (10.45GB free)|
|Process Argv|--crash-reporter-id 919755b5-939f-4f18-a179-ea7f18819776|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: somerset.csail.mit.edu' could not be established  Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by kycutler** [comment]
Hi @Ar-Kareem, thanks for reporting this issue!

We have issued a fix, available now in the latest Data Wrangler pre-release version `1.15.0`. You can opt into the pre-release via the extension page in VS Code:
![Image](https://github.com/user-attachments/assets/cbb33953-7abe-45fc-8bc1-0421c1eb64d4)

Closing this issue, but feel free to reopen if you still see a problem!
