### ISSUE TITLE
feature request: add *.csv.gz support.

### ISSUE THREAD

**Issue by songsammy** [microsoft/vscode-data-wrangler#362]
It is common that the downloaded data is compressed as gzip. And pandas support gzipped csv, So why not add support for gzipped file with extension ".csv.gz"?

**Comment by pwang347** [comment]
Hi @songsammy, thank you for opening this feature request! It sounds like what you're asking for falls under https://github.com/microsoft/vscode-data-wrangler/issues/250, so will close this as a duplicate. Please feel free to upvote the issue and subscribe and we will provide updates to this request there.

Thanks!
