### ISSUE TITLE
Please display the row headers when view a specific piece of data in the middle of the table

### ISSUE THREAD

**Issue by 17827063312** [microsoft/vscode-data-wrangler#365]
Type: <b>Feature Request</b>

# Behaviour

## Expected vs. Actual

When I place the table view at a specific position in the middle of the data table, I can only see the column headers but not the row headers. This makes it very inconvenient for me to check the index values of specific data. I hope that when I view a specific piece of data in the middle of the table, the row headers can be displayed as well

# Diagnostic data

-   Jupyter extension version: 2024.10.0
-   Python extension version: 2024.22.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "1.3.5"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.14.0
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by pwang347** [comment]
Hi @17827063312, thank you for opening this feature request! It seems like you might be asking for the same thing as https://github.com/microsoft/vscode-data-wrangler/issues/246. I would encourage you to upvote and subscribe to the issue for updates.

Will close this one as duplicate for now. Thanks!
