### ISSUE TITLE
Unable to load dataframe

### ISSUE THREAD

**Issue by PlayfulPiano** [microsoft/vscode-data-wrangler#366]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

View dataframe in data wrangler.

Instead, gives error: Unexpected token '', "[32mOvera"... is not valid JSON

## Steps to reproduce:

Create dataframe, run in python debugger until breakpoint, right click dataframe in run & debug menu to open in data wrangler, gives error Unexpected token '', "[32mOvera"... is not valid JSON

     Store    Item Code
1      102  22389800000
2      102  21124400000
3      161  22389800000
4      161  21124400000
5      162  22389800000
...    ...          ...
1339  None         None
1340  None         None
1341  None         None
1342  None         None
1343  None         None

[1343 rows x 2 columns]

# Diagnostic data

-   Jupyter extension version: 2024.11.0
-   Python extension version: 2024.22.0
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
N/A
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.14.0
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1345U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (9.39GB free)|
|Process Argv|--crash-reporter-id 0550736f-c139-4c88-9107-9ac488208fed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by pwang347** [comment]
Hi @PlayfulPiano, thanks for opening this issue. Does this issue occur for all datasets, or just the one you were using?

E.g., are you able to load this one?
```python
df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
```

If the above one works, could you please share a small example code to reproduce the error? Thanks!

**Comment by PlayfulPiano** [comment]
Hi sorry, so it wasn't all dataframes but specifically ones I was generating based on some data manipulation after pulling it from an excel worksheet via openpyxl. But I did try using the prerelease version instead and that didn't have any loading issues. So my best guess is that it's something already fixed in dev.
