### ISSUE TITLE
Feature Request: Copying data cells

### ISSUE THREAD

**Issue by irekkosek** [microsoft/vscode-data-wrangler#43]
Hi! 
As of now you are only being able to copy one cell of data. Could you add multiple cell data copying feature (row and column wise) like in excel for ex.?
Also Great work guys! Keep it up!

**Comment by pwang347** [comment]
Hi @irekkosek, thank you for the great suggestion!

We have added support for copying one or more rows and it will be available in next week's pre-release version.

Please note that we will not add column copying in this iteration, as it is not possible without loading more data upfront (which can be slow).

For Excel-like sub-selection copying, we have on our roadmap an update to selection states in the grid and the copy functionality will be there once implemented as well.

Thanks for trying Data Wrangler!
