### ISSUE TITLE
Duplicate values in the first column overwrite rows

### ISSUE THREAD

**Issue by dokutoshi** [microsoft/vscode-data-wrangler#46]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual
The same Image_name is used to test model
Should have 2 rows per the csv
Actual: Only 1 row
## Steps to reproduce:

1. Open a csv with Datawrangler with the first column identical for both rows.

# Diagnostic data

-   Jupyter extension version: 2023.4.1011241018
-   Python extension version: 2023.9.11371007
-   .NET Install Tool for Extension Authors extension version: 1.6.0

<details>

<p>

```
XXX
```

</p>
</details>

Extension version: 0.8.0
VS Code version: Code - Insiders 1.79.0-insider (Universal) (02298ef4180f2a5db39e0cb6288382860b96a596, 2023-05-11T05:26:00.234Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 4.14.301-224.520.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 7, 10|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id e016c85b-9a68-4860-9d1f-f603a9ff439d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: DL_OCR_Leo_G4DN_Main|
|OS|Linux x64 4.14.301-224.520.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (32 x 3103)|
|Memory (System)|124.47GB (37.91GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
f08j5886:30680471
57b77579:30687741
pythonfmttext:30716741
[PROD_INFER_ImageList-sandbox.csv](https://github.com/microsoft/vscode-data-wrangler/files/11504394/PROD_INFER_ImageList-sandbox.csv)

pythoncmvfstr:30726892
fixhidewlkth:30724384
hidesbindicator:30724476
pythongtdpath:30726887

```

</details>

**Comment by pwang347** [comment]
Hi @dokutoshi, I am using stable!

It seems like this is happening because Pandas `read_csv` is expecting a header row for the import - note that from the video you provided it doesn't seem like there is a header row, and only two rows with data.

If you are not able to modify the CSV file directly, a workaround could be to write the following code and execute it in an IPYNB file and then launch it in Data Wrangler:
```
import pandas as pd
df = pd.read_csv("PROD_INFER_ImageList-All-Top14.V1-testdata_model11_sandbox.csv", names=["col1", "col2", "col3", "col4", "col5", "col6", "col7"])
df
```

Please note that custom CSV import options are on our roadmap and is something that we are investigating. Thanks!

**Comment by dokutoshi** [comment]
> Hi @dokutoshi, I am using stable!
> 
> It seems like this is happening because Pandas `read_csv` is expecting a header row for the import - note that from the video you provided it doesn't seem like there is a header row, and only two rows with data.
> 
> If you are not able to modify the CSV file directly, a workaround could be to write the following code and execute it in an IPYNB file and then launch it in Data Wrangler:
> 
> ```
> import pandas as pd
> df = pd.read_csv("PROD_INFER_ImageList-All-Top14.V1-testdata_model11_sandbox.csv", names=["col1", "col2", "col3", "col4", "col5", "col6", "col7"])
> df
> ```
> 
> See the documentation here: ![image](https://user-images.githubusercontent.com/8560030/239360354-a5bfb0e2-b1dd-48d4-a29f-ef142c8b1eca.png)
> 
> Please note that custom CSV import options are on our roadmap and it is something that we are investigating. Thanks!

Makes sense.  I recommend the Data Wrangler tool should handle this for robustness.  I will modified the CSV.

Thank you,

Leo
