### ISSUE TITLE
What is the license status of this codebase

### ISSUE THREAD

**Issue by paddymul** [microsoft/vscode-data-wrangler#47]
The source code is available,  and there is mention of  VS Marketplace Terms of Use at http://aka.ms/VSMarketplace-TOU
MICROSOFT PRE-RELEASE LICENSE TERMS

But it is unclear if this is close to BSD licensing, AGPL, or something else.

I'm trying to get the licensing description correct for the related projects section of
https://buckaroo-data.readthedocs.io/en/latest/FAQ.html

**Comment by pwang347** [comment]
Hi @paddymul, thanks for the question!

Please note that the source code is not open source, but rather it is closed source (and so there is no license for it).
The license for the extension artifact is under the marketplace license, please feel free to link directly to it if needed.

**Comment by davinsannes** [comment]
@pwang347 What license do you plan to use when this extension is released (vs. preview)? Is the plan for it to be free for commercial use?
