### ISSUE TITLE
Wrong column selected when choosing target columns

### ISSUE THREAD

**Issue by Goodernews** [microsoft/vscode-data-wrangler#51]
## Environment data

- VS Code version: 1.78.2
- Data Wrangler Extension version: 0.8.0
- Jupyter Extension version: v2023.4.1011241018
- Python Extension version: v2023.8.0
- OS: Windows_NT x64 10.0.2261
- Pandas version: 2.0.1
- Python and/or Anaconda version: 13.1
- Type of virtual environment used: N/A

## Expected behaviour

Exact column selection. 

## Actual behaviour

When attempting to select a column, data wrangler deselects another.

https://github.com/microsoft/vscode-data-wrangler/assets/40648132/5ac839a5-b91e-4da3-bcae-b343032cc7cd

## Steps to reproduce:

```py
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv"
sample = pd.read_csv(url)

sample.head()
```

1. Run the code above
2. Select "Fill missing values"
3. Select `hdpe` or another numeric column. 
4. Select other columns until data wrangler deselects columns

## Logs

N/A

**Comment by pwang347** [comment]
Hi @Goodernews, I can confirm that this repros. We will look into it - thanks!

**Comment by pwang347** [comment]
This issue will be fixed in the upcoming pre-release. Thanks!
