### ISSUE TITLE
Can't see data or perform operations when index is not unique 

### ISSUE THREAD

**Issue by tkephart96** [microsoft/vscode-data-wrangler#52]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

Expected: Ability to see data values and perform operations (i.e. reset_index).

Actual: Data values take on their respective column names and operations either try to preview/run forever or fail to preview/run (i.e. reset_index gives error: Failed to update data frame: Reindexing only valid with uniquely valued Index objects)

## Steps to reproduce:

1. Open Jupyter notebook (.ipynb)
2. Import Pandas
3. Set a variable to a pandas dataframe where the index is not unique
4. Open the datafframe in Data Wrangler
a. data values take on column names
5. Custom operation: df = df.reset_index()
a. Error: Failed to update data frame: Reindexing only valid with uniquely valued Index objects

# Diagnostic data

-   Jupyter extension version: 2023.4.1011241018
-   Python extension version: 2023.8.0
-   .NET Install Tool for Extension Authors extension version: 1.6.0

<details>

<p>

```
Tried to do some time series analysis where the index is in datetime format and sometimes the datetime index will not be completely unique (i.e. multiple days for index but row data is still unique). As long as index is unique, there is no issue, but when not unique values display column names and operations fail to execute. No issue when opening csv in Data Wrangler since it seems to reset index or add a unique index when doing so.
```

</p>
</details>

Extension version: 0.8.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.5.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id cd9056ec-1f5b-4d8b-a276-ab5253fd3076|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by pwang347** [comment]
Hi @tkephart96!
We've addressed this issue and it will be available in the next pre-release. Please note that when using non-unique indices there will be some cases where we aren't able to always generate a nice preview and instead will just show the newer data.

Thanks for trying Data Wrangler!
