### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by oleksandrzelentsov** [microsoft/vscode-data-wrangler#54]
Cannot install extension with message:
![image](https://github.com/microsoft/vscode-data-wrangler/assets/8092489/9a047ff3-d1cf-42ee-9a1a-fc45c7cf8aac)

**Comment by jruales** [comment]
@oleksandrzelentsov Thanks for trying Data Wrangler!

The Data Wrangler extension currently requires VS Code version 1.77.0 or above. Please update your VS Code to be able to install the extension. You can do that from the "Help" menu on Windows and Linux and from the "Code" menu on Mac. See here for more information: https://code.visualstudio.com/docs/setup/setup-overview#_update-cadence
