### ISSUE TITLE
Context menu does not appear when right clicking in code preview

### ISSUE THREAD

**Issue by Goodernews** [microsoft/vscode-data-wrangler#55]
## Environment data

- VS Code version: 1.78.2
- Data Wrangler Extension version: 0.10.0
- Jupyter Extension version: v2023.4.1011241018
- Python Extension version: v2023.8.0
- OS: Windows_NT x64 10.0.2261
- Pandas version: 2.0.1
- Python and/or Anaconda version: 13.1
- Type of virtual environment used: N/A

## Expected behaviour

When in "Preview code for "Right click opens the context menu where copy command can be found.

## Actual behaviour

The context menu does not appear after right clicking. 

https://github.com/microsoft/vscode-data-wrangler/assets/40648132/9eccb9b5-efa0-4d85-907a-f9df44a836b4

## Steps to reproduce:

```py
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv"
sample = pd.read_csv(url)

sample.head()
```

1. Run the code above
2. Select "Filter"
3. Select `year` or another column. 
4. Filter to a specific year
5. Accept the change
6. Preview code for all steps
7. Highlight and right click for context menu

## Logs

N/A

**Comment by kycutler** [comment]
Hi @Goodernews, thanks for reporting this issue!

I can confirm this repros -- we are working on a fix now. It should go into the next release of Data Wrangler. I will update here when it is available.

**Comment by kycutler** [comment]
This is now in Data Wrangler stable 0.12.0.
