### ISSUE TITLE
Closing Data Wrangler tab, changes original notebook view

### ISSUE THREAD

**Issue by andyp05** [microsoft/vscode-data-wrangler#56]
## Environment data

Version: 1.80.0-insider (user setup)
Commit: db6bcdf309cc1565c502a54b73c33a63bdabfbd8
Date: 2023-06-09T05:21:13.157Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23475
Data Wrangler Extension version: v0.11.0
Windows 11

## Expected behavior

Closing wrangler tab to return to notebook in viewing state that was set before opening wrangler.

## Actual behavior

When the notebook tab regains focus, the Explorer left hand tab opens even if it was closed when 'Wrangler' button was hit. 
Additionally, the bottom section opens to even if 'Variables' was last opened.

## Steps to reproduce:

1. create notebook.
2. call df.head() on a dataframe.
3. Close 'Explorer' on the left and all panels at the bottom.
4. Hit 'Launch Data Wrangler'
5. Close data wrangler tab.

When original notebook regains focus, the explorer panel on the left is open, and the 'Problems, output, debug...' panel at the bottom is open.

**Comment by pwang347** [comment]
Hi @andyp05, thanks for opening this issue! This is the default behaviour for VS Code panels, but there are definitely ways for us to improve the experience here. We'll look into it.

**Comment by pwang347** [comment]
Opened an issue here for VS Code to add an API for this: https://github.com/microsoft/vscode/issues/186581

**Comment by pwang347** [comment]
Hi @andyp05, just wanted to let you know that there's now a setting to disable this behaviour in pre-release version 1.13.3. It would be great if you could try this out following the instructions [here](https://github.com/microsoft/vscode-data-wrangler/issues/96#issuecomment-2487056292) and let me know if you have any additional feedback. Thanks!

**Comment by andyp05** [comment]
The original problem partially still exists. 

open a notebook.
collapse left panel of files.
open data wrangler.
close DW tab.
When original notebook regains focus, the explorer panel on the left reopens, Now, the 'Problems, output, debug...' panel at the bottom does not reopen.

So, problem is half solved.

**Comment by pwang347** [comment]
Hi @andyp05 can you confirm if you've tried **unchecking** the setting here?
![Image](https://github.com/user-attachments/assets/3fb2e7d1-51f7-4040-aeb3-137305aca254)

The other half of the problem should be resolved here as well. Thanks!

**Comment by andyp05** [comment]
Confirmed.  It is working. I thought I had unchecked before testing. Thanks.
