### ISSUE TITLE
Sidebar reopening on every click when data wrangler window is active

### ISSUE THREAD

**Issue by inigohidalgo** [microsoft/vscode-data-wrangler#58]
## Environment data

-   VS Code version: 1.79.1
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.10.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1001582324
-   Python Extension version (available under the Extensions sidebar): v2023.10.1
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.4 LTS
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

*Additional environment data*: I am connecting through ssh to a remote development image, my host OS is Windows 10

## Expected behaviour

I minimize the sidebar with Ctrl + B, and I would expect it to stay hidden until I reopen it.

## Actual behaviour

When I have a Wrangler tab active, it forcefully reopens the sidebar whenever I interact with the VSCode editor area. If I switch to another tab of the sidebar, like source control or "Search", it will forcefully return me to the Wrangler section. This only happens the first time I minimize the sidebar, if I minimize it again without clicking in the Wrangler editor the sidebar will stay minimized.

## Steps to reproduce:

See GIF:

![GIF showing what happens](https://i.imgur.com/zv2i201.gif)

**Comment by jmew** [comment]
Thanks for the feedback @inigohidalgo!

Just to clarify, when you are working in another tab and minimize the side panel, and you go back to Data Wrangler, would you want the side bar to open again or would you want to have it remain minimized?

For the scenario when you leave Data Wrangler again, we should try to preserve your previous settings for the sidebar (i.e. if it should be minimized or not) so this is something we can investigate as well.

**Comment by pwang347** [comment]
Hi @inigohidalgo! The fix for the issue mentioned in the description should be available in the next pre-release version. Thanks for reporting!
