### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by MartinSher** [microsoft/vscode-data-wrangler#60]
Is there a way to run the wrangler with parameters to, for example, read a csv file in a particular folder, pass a date etc

**Comment by pwang347** [comment]
Hi @MartinSher! Thanks for the question and apologies for the late response.
In general, for full flexibility the best option at the moment is to write Python code in a Jupyter notebook to produce a Pandas DataFrame.

```python
import pandas as pd

# read CSV file in particular folder
df = pd.read_csv("your-folder-path-here")

# pass in a date column
datetime_series = pd.Series(np.append(pd.date_range('2012-1-1', periods=9, freq='D').to_numpy(), [pd.NaT]), dtype="datetime64[ns]")
df["date_col"] = datetime_series

# putting this at the bottom of the cell will show a Data Wrangler launch button in VS Code
df
```

Hopefully this answers your question - if not please let me know!

**Comment by pwang347** [comment]
Closing for now due to inactivity, please feel free to reopen as needed. Thanks!
