### ISSUE TITLE
Data Wrangler + Synapse extension for Fabric? 

### ISSUE THREAD

**Issue by rabbyn** [microsoft/vscode-data-wrangler#61]
@jmew is there any plan to get a tighter integration of Data Wrangler and [SynapseVScode] (https://github.com/microsoft/SynapseVSCode) from @qixwang ? That would help to streamline data wrangling operations on #Fabric lakehouse

**Comment by qixwang** [comment]
@rabbyn  thanks for the feedback..
 once you have the two extension( Data Wrangler and Synapse VS Code) installed, there are certain scenarios already been supported. for example, if you use the Fabric Notebook to load the LH data into a Spark data frame and covert it with the toPandas method, from the converted pandas df, you can activate the Data Wrangler, the generated code from the DW extension can be saved back to the same Fabric notebook. 

is there any other use case you like to support? maybe directly activate the DW extension from the certain Lakehouse table or .csv file?

**Comment by rabbyn** [comment]
Hi @qixwang yes true there is already some scenarios where it works, you're right. Maybe activating the Data Wrangler directly from a Lakehouse table would be nice indeed. If I think about something else I will share here. Thanks

**Comment by qixwang** [comment]
@rabbyn below are the possible scenario we are considering to support, please let me know if these make sense to you
1) activating the DW directly from a LH table/csv 
2) provide a entry to active the DW if a Spark Dataframe is available in the Fabric Notebook output cell, user dont need to manually do the conversion by themself

qixiao

**Comment by pwang347** [comment]
Closing this issue, as it seems to be addressed - please feel free to reopen if needed. Cheers!
