### ISSUE TITLE
Cannot Open .pq Files in Data Wrangler

### ISSUE THREAD

**Issue by BradFrueh** [microsoft/vscode-data-wrangler#67]
## Environment data

- VS Code version: 1.80
- Data Wrangler Extension version (available under the Extensions sidebar): v0.12.0
- Jupyter Extension version (available under the Extensions sidebar): v2023.6.1001861915
- Python Extension version (available under the Extensions sidebar): v2023.13.11871009
- OS (Windows | Mac | Linux distro) and version: Windows 10
- Pandas version: 1.3.5
- Python version: 3.913
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): (N/A)

## Expected behavior

Right clicking a parquet file with the shorthand version of the file extension, '.pq' instead of '.parquet', should provide an option to 'Open in Data Wrangler'.

## Actual behavior

Right clicking a parquet file with the full extension '.parquet' provides the 'Open in Data Wrangler' option in the drop down menu but does not provide an option when the file uses the shorter extension '.pq'.

## Steps to reproduce:

1. Install Data Wrangler extension and necessary prerequisites (Python, Pandas).
2. In the file explorer pane, right click a .pq file.
3. Notice that 'Open in Data Wrangler' option is not present.

## Logs

<details>

No error messages or logs related to the issue.

**Comment by pwang347** [comment]
Hi @BradFrueh, thanks for opening this request and trying out Data Wrangler!

Unfortunately the `.pq` file extension is also used for [Power Query](https://learn.microsoft.com/en-us/power-query/power-query-sdk-vs-code) so this isn't something we would be able to support without adding confusion.

For now, we would recommend just renaming the file to `.parquet`. We apologize for the inconvenience!
