### ISSUE TITLE
Feature Request: create a datetime from existing string columns

### ISSUE THREAD

**Issue by Kevin-McIsaac** [microsoft/vscode-data-wrangler#68]
Add an operation to create a datetime from existing string columns. For example I might a csv with Year and Month and want to create a new column that is a date time. I was able to do this useing "Create column from formula" but I needed to know to inster the code df['Date'] = pd.to_datetime(dict(year=df.Year, month=df.Month, day=df.Day))

It would be nice to just have a create datetime and then select the columns that are the Year, Month and Day or be able to provide a constant value for any of these.

**Comment by pwang347** [comment]
Hi @Kevin-McIsaac, thanks for the suggestion! We'll be investigating what we can do to improve our handling of datetime columns and will include this feedback there.

An alternative way to achieve this currently is to use the  `New column by example` operation to select the columns and provide a string result for the datetime and then cast it, but definitely not ideal.

**Comment by Kevin-McIsaac** [comment]
I tried `New column by example` but could not figure out how to make that work. Perhaps you have a video on this feature?

**Comment by pwang347** [comment]
Of course, please see the GIF below:
![newcolumnbyexample](https://github.com/microsoft/vscode-data-wrangler/assets/8560030/b038de80-10da-4cc6-bda5-25009ace6dd7)

The basic idea is that you can provide one or more examples for the output value (currently only strings) based on the targeted input columns and a program is inferred based on that. Generally speaking, you'll probably get better results from this operation if your column doesn't have too much noise in it.

**Comment by Kevin-McIsaac** [comment]
This example was most helpful!
