### ISSUE TITLE
Feature Request: Delete any Cleaning Step not just the last

### ISSUE THREAD

**Issue by Kevin-McIsaac** [microsoft/vscode-data-wrangler#72]
I'd like to be able to delete any cleaning step not just the last. Some times this will work other times it will create downstream issue. If I can insert steps anywhere or move steps I can easily fix this.

**Comment by pwang347** [comment]
Thanks for opening this request @Kevin-McIsaac! This feature is already in our backlog and we'll provide progress updates to it on this issue.
