### ISSUE TITLE
Data Wrangler on pandas df object and not on data file (like .csv)

### ISSUE THREAD

**Issue by DAT-FYAYC** [microsoft/vscode-data-wrangler#76]
## Environment data

-   VS Code version: Version: 1.80.1
-   Data Wrangler Extension version (available under the Extensions sidebar): v0.14.0
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Pandas version: 1.5.3
-   Python and/or Anaconda version: Python 3.10

## Expected behaviour
Data Wrangler can only be used on the original data (e.g. .csv). Would be great to use Data Wrangler within a jupyter notebook at any point. Meaning to use data wrangler on any pandas df object within a notebook. This would help to use transformed views of the data instead of only the original data without the need to save the df as a file.

## Actual behaviour
Data Wrangler can only be used on files like .csv and not on pandas df objects.

**Comment by pwang347** [comment]
Hi @DAT-FYAYC, thanks for opening this issue!

It's actually already possible to open any Pandas DataFrame, please refer to this section [here](https://github.com/microsoft/vscode-data-wrangler#launching-data-wrangler-from-a-jupyter-notebook).

Currently we require specific syntaxes to trigger the launch button, but we'll be looking to expand the options here in the future. Thanks for trying Data Wrangler!

**Comment by DAT-FYAYC** [comment]
The issue seems to appear kind of random. Might be related when using multiple VS Code windows. At least this is my feeling. Can only use Data Wrangler in the window where I first trigger the specific syntaxes to launch the button.

**Comment by pwang347** [comment]
Is it possible that you're running into this issue as well? https://github.com/microsoft/vscode-data-wrangler/issues/80 if so, you might be able to try the workaround in that thread for now and see if that fixes it for you.

Otherwise do you mean that if you have multiple windows open, only one of them shows the button?

**Comment by DAT-FYAYC** [comment]
I just tested it with two windows again. I do have the same issue within a single window as well as within multiple windows. Using sleep did help, so it might be the same underlying issue as in #80.

**Comment by pwang347** [comment]
Got it, thank you for confirming! Let me close this issue for now and will continue the discussion in https://github.com/microsoft/vscode-data-wrangler/issues/80.
