### ISSUE TITLE
Open dataframe does not reload new data, if the dataframe view is open

### ISSUE THREAD

**Issue by dokutoshi** [microsoft/vscode-data-wrangler#77]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

Expected behavior: Dataframe reloads with new data
Actual: Dataframe does not reload and maintains old view of content

## Steps to reproduce:

1. Create a pandas dataframe and Launch Data Wrangler
2. Update original dataframe and execute.
3. Depress Launch Data Wrangler
4. Check contents of Dataframe (view shows prior data)

# Diagnostic data

-   Jupyter extension version: 2023.6.1101941928
-   Python extension version: 2023.12.0
-   .NET Install Tool for Extension Authors extension version: 1.6.0

<details>

<p>

```
XXX
```

</p>
</details>

Extension version: 0.14.0
VS Code version: Code - Insiders 1.81.0-insider (fda972663af87b4d1dab87845e36c357738b44f9, 2023-07-25T08:14:58.320Z)
OS version: Darwin arm64 22.6.0
Modes:
Connection to 'ssh-remote+7b22686f73744e616d65223a22444c5f4f43525f4c656f5f50335f4d61696e5f436f7079227d' could not be established
Connection to 'ssh-remote+7b22686f73744e616d65223a22444c5f4f43525f4c656f5f50335f4d61696e5f4164616d227d' could not be established
Remote OS version: Linux x64 4.14.301-224.520.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id dff73d48-0b4d-45a8-98eb-6ce73bd1c7ec|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+7b22686f73744e616d65223a22444c5f4f43525f4c656f5f50335f4d61696e5f436f7079227d' could not be established

Connection to 'ssh-remote+7b22686f73744e616d65223a22444c5f4f43525f4c656f5f50335f4d61696e5f4164616d227d' could not be established

|Item|Value|
|---|---|
|Remote|SSH: DL_OCR_Leo_P3_New_Main|
|OS|Linux x64 4.14.301-224.520.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (32 x 1787)|
|Memory (System)|240.08GB (226.87GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
2i9eh265:30646982
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30792099
asynctok:30795849
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by pwang347** [comment]
Hi @dokutoshi, thanks for opening this issue! We'll look into fixing this.
