### ISSUE TITLE
"New operation" opens terminal panel for all opened files

### ISSUE THREAD

**Issue by ZupoLlask** [microsoft/vscode-data-wrangler#79]
While I understand that (even before Data Wrangler) once bottom panel (`Ctrl+J`) is open in a given tab/file, it remains open throughout all VS Code until it's closed somewhere, with Data Wrangler it feels particularly inconvenient getting bottom panel automatically opened whenever you alternate between other tabs back to Data Wrangler's.

Please mind that Data Wrangler will probably also be used frequently as a very capable data viewer inside VS Code (my use case, in this situation), besides the use case of being used as a data cleaning tool.

## Environment data

-   VS Code version: 1.80.2
-   Data Wrangler Extension version (available under the Extensions sidebar): 0.15.1
-   Jupyter Extension version (available under the Extensions sidebar): 2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar): 2023.12.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Pandas version: 2.0.3
-   Python and/or Anaconda version: 3.10.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behaviour

I think that "New operation" bottom panel should only be opened when one's triggers "Custom operation" functionality (from "Operations" side bar).

I accept that probably this behaviour is due to you guys wanting to have this functionality more "visible"/"accessible" in terms of UX, so if that's the case, as an easy compromise I think it's OK to keep this behaviour for the first time one's opens a new Data Wrangler instance and until bottom panel is explicitely closed. After that point, Data Wrangler bottom panel should only opened again by user "toggle panel" action, by double clicking a given cleaning step (from "Cleaning steps" side bar) or by clicking "Custom operation" from "Operations" side bar. 

Maybe you'll want to consider adding a easily accessible persistent "preview code" switch right next to "preview code for all steps" to control this behaviour.

Either way, if in the future Data Wrangler will always need bottom panel for standard (not advanced/debug) usage, I really think you must consider to restore bottom panel status when a user is alternating from Data Wrangler's tab to other open tabs.

## Actual behaviour

When you have the bottom panel (Issues, Output, Terminal, Debug Console, etc.) closed, as soon as you alternate to Data Wrangler's tab it's opened and you'll have to close it every time you alternate away from Data Wrangler's tab, even if you didn't need to use "New operation" panel.

## Steps to reproduce:

1. With VS Code bottom panel closed, run the following Python code in a Jupyter cell: `import pandas as pd; df = pd.DataFrame(['a', 'b', 'c'], columns=['A']); df`
2. Click `Launch Data Wrangler` button
3. Notice that "Data Wrangler" bottom panel is now opened, displaying "New operation" code preview
4. Alternate back to original Jupyter tab and notice "Terminal" bottom panel is now (inconveniently) opened

**Comment by pwang347** [comment]
Hi @ZupoLlask, thanks for the great feedback! We'll take this on our backlog to investigate how we can improve the panel experience.

**Comment by pwang347** [comment]
Hi @ZupoLlask, it's been a while but just wanted to provide an update that while we weren't able to programmatically determine when the panel should be collapsed or not (e.g., see lack of traction in https://github.com/microsoft/vscode/issues/214639) we've added a new setting in pre-release 1.13.3 that should help address this issue.

For more details, see https://github.com/microsoft/vscode-data-wrangler/issues/96#issuecomment-2487056292

Thanks!

**Comment by ZupoLlask** [comment]
Hi!

This behavior disappeared several months ago.

It seems fixed now. 🙏

**Comment by pwang347** [comment]
Ah yes that's right, the bottom panel won't be shown if you stay in the new viewing mode (the new setting might still help if you are opening local data files or would like to avoid having the side panel pop up as well though). Great to hear that the issue is resolved for you!
