### ISSUE TITLE
Feature request: support Launch in an interactive window

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-data-wrangler#82]
I normally do not like show results in the notebook, but send codes to the interactive window as a console. 
This would be very helpful to have "Launch Data Wrangler" in the interactive window. 

<img width="1476" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/4111978/4676a63e-578b-4f3a-87c1-a3076d0f8e89">

**Comment by pwang347** [comment]
Hi @Fred-Wu, this issue is being tracked in https://github.com/microsoft/vscode-data-wrangler/issues/18 so I will close this as a duplicate. Thanks!
