### ISSUE TITLE
"Launch Data Wrangler" only appears in the first time of execusion in a notebook. 

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-data-wrangler#83]
## Environment data

-   VS Code version: 1.80.2
-   Data Wrangler Extension version: 0.14.0
-   Jupyter Extension version: v2023.6.1101941928
-   Python Extension version: v2023.12.0
-   MacOS M1 and version: 13.5

Run first time in a cell

<img width="618" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/4111978/05cbacef-9086-4279-ad0c-1658ddce3c71">

Run second time in the same cell

<img width="618" alt="image" src="https://github.com/microsoft/vscode-data-wrangler/assets/4111978/4ae01396-ee33-4919-846e-fcb8db97e009">

**Comment by pwang347** [comment]
Hi @Fred-Wu, thanks for trying Data Wrangler! We are currently tracking this problem in https://github.com/microsoft/vscode-data-wrangler/issues/80 so I will close this issue as a duplicate.
