### ISSUE TITLE
Feature request - Accept .TSV files

### ISSUE THREAD

**Issue by rmallampalli** [microsoft/vscode-data-wrangler#94]
Thanks for the amazing extension! Would love it if .TSV files were supported in the open file UI. Would be even better if the delimiter character were auto-detected from the CSV file.

**Comment by pwang347** [comment]
Hi @rmallampalli, thanks for opening this request! We've added this to our list of items to work on, and will provide any updates here.

**Comment by kycutler** [comment]
Hi @rmallampalli, good news! This is now supported in the latest pre-release version of Data Wrangler. You can open Data Wrangler directly from a TSV file by any of the same ways as from a CSV. In addition, Data Wrangler will now automatically detect the delimiter within files with the `csv` extension.

We welcome any further feedback you might have. Thanks again for opening this issue, and for trying Data Wrangler!
