### ISSUE TITLE
Search and replace cannot apply nulls (so also cannot change to numerical datatype!)

### ISSUE THREAD

**Issue by TickboxPhil** [microsoft/vscode-data-wrangler#99]
## Environment data
Latest Versions on Windows 10. General issue anyway.

## Expected behaviour
Provide way to specify NaN, None or NULL in search/replace column

## Actual behaviour
Only the text of the above is substituted.

## Steps to reproduce:
1. Select Column and "Find and Replace"
2. Try entering NaN, None or NULL. Really need to put pd.NA, np.nan etc.

<p>
Basically there's no option, and typing null/NaN/NA/None or trying to use pandas/numpy pd.NA or np.nan also results in just the text being substituted.

If manually typing and importing numpy:
```
# Replace all instances of "--" with "np.NaN" in column: 'SecInIssue'
import numpy as np
df['SecInIssue'] = df['SecInIssue'].str.replace("--", np.nan, case=False, regex=False)
```
we get error:
```
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\core\strings\accessor.py:1523, in StringMethods.replace(self, pat, repl, n, case, flags, regex)
   1521 # Check whether repl is valid (GH 13438, GH 15055)
   1522 if not (isinstance(repl, str) or callable(repl)):
-> 1523     raise TypeError("repl must be a string or callable")
   1525 is_compiled_re = is_re(pat)
   1526 if regex or regex is None:
TypeError: repl must be a string or callable
```
Seems like the internal package is string only. Is there any way to replace a column value with nulls? 

Seems pretty crucial, especially as we can't update the column datatype to anything numerical without doing so - maybe I'm missing something?
</p>

**Comment by pwang347** [comment]
Hi @TickboxPhil, thanks for opening this issue!

I think as a workaround you should be able to run something like this:

```python
import numpy as np
df['SecInIssue'] = df['SecInIssue'].replace(to_replace ='--', value=np.nan)
```

Hopefully this helps.

As far as including this as an option for the `Find and replace` operation in Data Wrangler I will need to double-check with my team. I think the scenario definitely makes sense (e.g. you have a column that's being interpreted as a string when it should be numerical) and you want to convert those values to `np.nan` to be able to cast it afterwards. However, it might be a question of whether we want this to be a new operation altogether or to update the existing one since we already handle missing values separately.

Will keep you posted for any updates here, cheers!

**Comment by TickboxPhil** [comment]
Great - thanks @pwang347 that works, and can now also cast the column datatype numeric! Ah, so just a Python thing then (when going into manual mode), needed to avoid the .str method and streamline into .replace.

Good points too - v handy it has the missing value handling (can improved for various scenarios going forward - already like the "most common" option but "use average" probably even better), although as you know, the issue here is to get it to be properly missing (ie np.nan) in the first place! In this case, source data string "--" was used to blank out the value, but it could be any text like "None", "NA" etc. Now we have a solution, thanks, but handy to have as quick option!

It is a bit frustrating to not be able to go back into Data Wrangler (once left) from the .pynb (the only artefact file left from editing) - basically unless I'm missing something, you have to start all the steps from scratch again if you want to use the GUI options again. But maybe that will be added too (not critical yet) - it's a really handy tool as part of the data arsenal, another win for VSC!
